-- =============================================================================
-- MART_LOGISTICS_PERFORMANCE — Production Validation Checks
-- Target: SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE
-- Run after V2.6.0 is applied.
-- =============================================================================

-- V2.6.0 column contract: 29 columns, 60,000 rows, grain SHIPMENT_ID

-- =============================================================================
-- 1. STRUCTURAL CHECKS
-- =============================================================================

-- 1a. Row count
SELECT 'ROW_COUNT' AS check_name,
  COUNT(*) AS actual, 60000 AS expected,
  CASE WHEN COUNT(*) = 60000 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- 1b. Column count
SELECT 'COLUMN_COUNT' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_LOGISTICS_PERFORMANCE') AS actual,
  29 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_LOGISTICS_PERFORMANCE') = 29
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1c. Grain uniqueness
SELECT 'GRAIN_UNIQUENESS' AS check_name,
  (SELECT COUNT(*) FROM (
    SELECT SHIPMENT_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE
    GROUP BY SHIPMENT_ID HAVING COUNT(*) > 1)) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM (
    SELECT SHIPMENT_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE
    GROUP BY SHIPMENT_ID HAVING COUNT(*) > 1)) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1d. Null PK
SELECT 'NULL_SHIPMENT_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE WHERE SHIPMENT_ID IS NULL) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE WHERE SHIPMENT_ID IS NULL) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1e. Analysis date
SELECT 'ANALYSIS_AS_OF_DATE' AS check_name,
  NULL AS actual, NULL AS expected,
  CASE WHEN (SELECT COUNT(DISTINCT ANALYSIS_AS_OF_DATE) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) = 1
       AND (SELECT MIN(ANALYSIS_AS_OF_DATE) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) = '2026-09-30'
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 2. REFERENTIAL INTEGRITY
-- =============================================================================

-- 2a. FK: CARRIER_ID
SELECT 'FK_CARRIER_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE m
   WHERE m.CARRIER_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_CARRIER dc WHERE dc.CARRIER_ID = m.CARRIER_ID)
  ) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE m
   WHERE m.CARRIER_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_CARRIER dc WHERE dc.CARRIER_ID = m.CARRIER_ID)
  ) = 0 THEN 'PASS' ELSE 'FAIL' END AS result;

-- 2b. FK: ROUTE_ID
SELECT 'FK_ROUTE_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE m
   WHERE m.ROUTE_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_ROUTE dr WHERE dr.ROUTE_ID = m.ROUTE_ID)
  ) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE m
   WHERE m.ROUTE_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_ROUTE dr WHERE dr.ROUTE_ID = m.ROUTE_ID)
  ) = 0 THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 3. IS_ON_TIME PRESERVATION
-- =============================================================================

SELECT 'IS_ON_TIME_PRESERVATION' AS check_name,
  NULL AS actual, NULL AS expected,
  CASE WHEN
    (SELECT SUM(CASE WHEN IS_ON_TIME = TRUE THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) =
    (SELECT SUM(CASE WHEN IS_ON_TIME = TRUE THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT)
    AND
    (SELECT SUM(CASE WHEN IS_ON_TIME = FALSE THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) =
    (SELECT SUM(CASE WHEN IS_ON_TIME = FALSE THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT)
    AND
    (SELECT SUM(CASE WHEN IS_ON_TIME IS NULL THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) =
    (SELECT SUM(CASE WHEN IS_ON_TIME IS NULL THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT)
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 4. RECONCILIATION
-- =============================================================================

-- 4a. SHIPPING_COST
SELECT 'SHIPPING_COST_RECONCILE' AS check_name,
  (SELECT SUM(SHIPPING_COST) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) AS mart_total,
  (SELECT SUM(SHIPPING_COST) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT) AS source_total,
  CASE WHEN (SELECT SUM(SHIPPING_COST) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) =
       (SELECT SUM(SHIPPING_COST) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT)
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 4b. ROUTE_DEVIATION_EVENT_COUNT
SELECT 'ROUTE_DEVIATION_RECONCILE' AS check_name,
  (SELECT SUM(ROUTE_DEVIATION_EVENT_COUNT) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) AS mart_total,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT WHERE EVENT_TYPE = 'ROUTE_DEVIATION') AS source_total,
  CASE WHEN (SELECT SUM(ROUTE_DEVIATION_EVENT_COUNT) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) =
       (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT WHERE EVENT_TYPE = 'ROUTE_DEVIATION')
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 4c. DELAY_REPORTED_EVENT_COUNT
SELECT 'DELAY_REPORTED_RECONCILE' AS check_name,
  (SELECT SUM(DELAY_REPORTED_EVENT_COUNT) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) AS mart_total,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT WHERE EVENT_TYPE = 'DELAY_REPORTED') AS source_total,
  CASE WHEN (SELECT SUM(DELAY_REPORTED_EVENT_COUNT) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) =
       (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT WHERE EVENT_TYPE = 'DELAY_REPORTED')
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 5. DELAY / TRANSIT NULL CONSISTENCY
-- =============================================================================

-- 5a. DELIVERY_DELAY_HOURS only when both timestamps present
SELECT 'DELIVERY_DELAY_NULL_CONSISTENCY' AS check_name,
  SUM(CASE WHEN (ACTUAL_DELIVERY_AT IS NULL OR PLANNED_DELIVERY_AT IS NULL) AND DELIVERY_DELAY_HOURS IS NOT NULL
      THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN (ACTUAL_DELIVERY_AT IS NULL OR PLANNED_DELIVERY_AT IS NULL) AND DELIVERY_DELAY_HOURS IS NOT NULL
      THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- 5b. DEPARTURE_DELAY_HOURS only when both timestamps present
SELECT 'DEPARTURE_DELAY_NULL_CONSISTENCY' AS check_name,
  SUM(CASE WHEN (ACTUAL_DEPARTURE_AT IS NULL OR PLANNED_DEPARTURE_AT IS NULL) AND DEPARTURE_DELAY_HOURS IS NOT NULL
      THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN (ACTUAL_DEPARTURE_AT IS NULL OR PLANNED_DEPARTURE_AT IS NULL) AND DEPARTURE_DELAY_HOURS IS NOT NULL
      THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- 5c. TRANSIT_VARIANCE_HOURS only when both transit hours present
SELECT 'TRANSIT_VARIANCE_NULL_CONSISTENCY' AS check_name,
  SUM(CASE WHEN (ACTUAL_TRANSIT_HOURS IS NULL OR PLANNED_TRANSIT_HOURS IS NULL) AND TRANSIT_VARIANCE_HOURS IS NOT NULL
      THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN (ACTUAL_TRANSIT_HOURS IS NULL OR PLANNED_TRANSIT_HOURS IS NULL) AND TRANSIT_VARIANCE_HOURS IS NOT NULL
      THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- =============================================================================
-- 6. DISTINCT_ORDER_COUNT SANITY
-- =============================================================================

-- All shipments should have at least 1 order (every shipment has shipment lines)
SELECT 'DISTINCT_ORDER_COUNT_GE_1' AS check_name,
  SUM(CASE WHEN DISTINCT_ORDER_COUNT < 1 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN DISTINCT_ORDER_COUNT < 1 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- =============================================================================
-- 7. FAN-OUT DETECTION
-- =============================================================================

SELECT 'FAN_OUT_DETECTION' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) AS actual,
  60000 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) = 60000
  THEN 'PASS' ELSE 'FAIL' END AS result;
