-- =============================================================================
-- MART_CUSTOMER_IMPACT — Production Validation Checks
-- Target: SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT
-- Run after V2.1.0 is applied.
-- =============================================================================

-- V2.1.0 column contract: 34 columns, 1500 rows, grain CUSTOMER_ID

-- 1. Structural
SELECT 'ROW_COUNT' AS check_name, COUNT(*) AS actual, 1500 AS expected,
  CASE WHEN COUNT(*) = 1500 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;

SELECT 'COLUMN_COUNT' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_CUSTOMER_IMPACT') AS actual,
  34 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_CUSTOMER_IMPACT') = 34
  THEN 'PASS' ELSE 'FAIL' END AS result;

SELECT 'GRAIN_UNIQUENESS' AS check_name,
  (SELECT COUNT(*) FROM (SELECT CUSTOMER_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1)) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM (SELECT CUSTOMER_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1)) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

SELECT 'NULL_CUSTOMER_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT WHERE CUSTOMER_ID IS NULL) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT WHERE CUSTOMER_ID IS NULL) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 2. Reconciliation
SELECT 'TOTAL_ORDERS' AS check_name,
  (SELECT SUM(TOTAL_ORDER_COUNT) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT) AS actual,
  50000 AS expected,
  CASE WHEN (SELECT SUM(TOTAL_ORDER_COUNT) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT) = 50000
  THEN 'PASS' ELSE 'FAIL' END AS result;

SELECT 'ANALYSIS_AS_OF_DATE' AS check_name, NULL AS actual, NULL AS expected,
  CASE WHEN (SELECT COUNT(DISTINCT ANALYSIS_AS_OF_DATE) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT) = 1
       AND (SELECT MIN(ANALYSIS_AS_OF_DATE) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT) = '2026-09-30'
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 3. Monetary
SELECT 'MONETARY_LATE_LE_ACTIVE' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT WHERE LATE_AFFECTED_ORDER_VALUE > ACTIVE_ORDER_VALUE) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT WHERE LATE_AFFECTED_ORDER_VALUE > ACTIVE_ORDER_VALUE) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

SELECT 'MONETARY_OVERDUE_LE_OUTSTANDING' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT WHERE OVERDUE_OUTSTANDING_VALUE > OUTSTANDING_VALUE) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT WHERE OVERDUE_OUTSTANDING_VALUE > OUTSTANDING_VALUE) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

SELECT 'MONETARY_OVERDUE_LE_LATE' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT WHERE OVERDUE_OUTSTANDING_VALUE > LATE_AFFECTED_ORDER_VALUE) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT WHERE OVERDUE_OUTSTANDING_VALUE > LATE_AFFECTED_ORDER_VALUE) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 4. Fulfillment
SELECT 'FULFILLMENT_PCT_BOUNDS' AS check_name,
  SUM(CASE WHEN FULFILLMENT_PCT > 100 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN FULFILLMENT_PCT > 100 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;
