-- =============================================================================
-- MART_SUPPLIER_RISK Validation Checks
-- Data-relative: no fixed row counts; validates against current Silver state.
-- =============================================================================

-- ===== STRUCTURAL CHECKS =====

-- 1. Column count = 50
SELECT 'Column count = 50' AS check_name,
       COUNT(*) AS column_count,
       CASE WHEN COUNT(*) = 50 THEN 'PASS' ELSE 'FAIL' END AS result
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_SUPPLIER_RISK'
  AND TABLE_CATALOG = 'SUPPLY_CHAIN_DW';

-- 2. Row count = DIM_SUPPLIER count (one row per supplier)
SELECT 'Row count matches DIM_SUPPLIER' AS check_name,
       (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK) AS mart_rows,
       (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.DIM_SUPPLIER) AS dim_rows,
       CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK)
                 = (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.DIM_SUPPLIER)
            THEN 'PASS' ELSE 'FAIL' END AS result;

-- 3. Grain uniqueness: one row per SUPPLIER_ID
SELECT 'Grain uniqueness (SUPPLIER_ID)' AS check_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT SUPPLIER_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT SUPPLIER_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 4. No NULL primary key
SELECT 'No NULL SUPPLIER_ID' AS check_name,
       SUM(CASE WHEN SUPPLIER_ID IS NULL THEN 1 ELSE 0 END) AS null_count,
       CASE WHEN SUM(CASE WHEN SUPPLIER_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- ===== SCENARIO CHECK: SUP-000016 =====

-- 5. SUP-000016 exists
SELECT 'SUP-000016 exists in mart' AS check_name,
       COUNT(*) AS cnt,
       CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK
WHERE SUPPLIER_ID = 'SUP-000016';

-- 6. SUP-000016 shows risk score increase (deterioration signal)
SELECT 'SUP-000016 risk score increase' AS check_name,
       RISK_SCORE_CHANGE,
       CASE WHEN RISK_SCORE_CHANGE > 0.20 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK
WHERE SUPPLIER_ID = 'SUP-000016';

-- 7. SUP-000016 flagged as at-risk
SELECT 'SUP-000016 IS_SUPPLIER_AT_RISK = TRUE' AS check_name,
       IS_SUPPLIER_AT_RISK,
       CASE WHEN IS_SUPPLIER_AT_RISK = TRUE THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK
WHERE SUPPLIER_ID = 'SUP-000016';

-- ===== FAN-OUT DETECTION =====

-- 8. Branch 1: supplier_performance produces exactly 1 row per supplier
SELECT 'No fan-out: supplier_performance' AS check_name,
       COUNT(*) AS suppliers_with_multiple,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM (
    SELECT SUPPLIER_ID, COUNT(*) AS cnt
    FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK
    GROUP BY SUPPLIER_ID
    HAVING cnt > 1
);

-- 9. Branch 3: inventory exposure position count reconciles to Silver
-- SUM of EXPOSED_INVENTORY_POSITION_COUNT across all suppliers should be >=
-- FACT_INVENTORY_SNAPSHOT row count (each inv position attributed to >= 1 supplier)
SELECT 'Inventory exposure reconciliation' AS check_name,
       SUM(EXPOSED_INVENTORY_POSITION_COUNT) AS mart_total_positions,
       (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT) AS silver_positions,
       CASE WHEN SUM(EXPOSED_INVENTORY_POSITION_COUNT) >=
                 (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT)
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 10. Branch 5: shipment exposure count per supplier <= total Silver shipments
SELECT 'Shipment exposure bounded by Silver' AS check_name,
       MAX(EXPOSED_SHIPMENT_COUNT) AS max_per_supplier,
       (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT) AS total_shipments,
       CASE WHEN MAX(EXPOSED_SHIPMENT_COUNT) <=
                 (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT)
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- ===== SEVERITY METRIC BOUNDS =====

-- 11. LOW_INVENTORY_EXPOSURE_PCT between 0 and 100 (or NULL)
SELECT 'LOW_INVENTORY_EXPOSURE_PCT bounds' AS check_name,
       SUM(CASE WHEN LOW_INVENTORY_EXPOSURE_PCT < 0 OR LOW_INVENTORY_EXPOSURE_PCT > 100 THEN 1 ELSE 0 END) AS out_of_bounds,
       CASE WHEN SUM(CASE WHEN LOW_INVENTORY_EXPOSURE_PCT < 0 OR LOW_INVENTORY_EXPOSURE_PCT > 100 THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 12. OUTSTANDING_EXPOSURE_PCT between 0 and 100 (or NULL)
SELECT 'OUTSTANDING_EXPOSURE_PCT bounds' AS check_name,
       SUM(CASE WHEN OUTSTANDING_EXPOSURE_PCT < 0 OR OUTSTANDING_EXPOSURE_PCT > 100 THEN 1 ELSE 0 END) AS out_of_bounds,
       CASE WHEN SUM(CASE WHEN OUTSTANDING_EXPOSURE_PCT < 0 OR OUTSTANDING_EXPOSURE_PCT > 100 THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 13. LATE_SHIPMENT_PCT between 0 and 100 (or NULL)
SELECT 'LATE_SHIPMENT_PCT bounds' AS check_name,
       SUM(CASE WHEN LATE_SHIPMENT_PCT < 0 OR LATE_SHIPMENT_PCT > 100 THEN 1 ELSE 0 END) AS out_of_bounds,
       CASE WHEN SUM(CASE WHEN LATE_SHIPMENT_PCT < 0 OR LATE_SHIPMENT_PCT > 100 THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 14. LOW_INVENTORY_POSITION_COUNT <= EXPOSED_INVENTORY_POSITION_COUNT
SELECT 'Low inv positions <= total positions' AS check_name,
       SUM(CASE WHEN LOW_INVENTORY_POSITION_COUNT > EXPOSED_INVENTORY_POSITION_COUNT THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN LOW_INVENTORY_POSITION_COUNT > EXPOSED_INVENTORY_POSITION_COUNT THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 15. ACTIVE_EXPOSED_OUTSTANDING_VALUE <= ACTIVE_EXPOSED_ORDER_VALUE
SELECT 'Outstanding value <= order value' AS check_name,
       SUM(CASE WHEN ACTIVE_EXPOSED_OUTSTANDING_VALUE > ACTIVE_EXPOSED_ORDER_VALUE + 0.01 THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN ACTIVE_EXPOSED_OUTSTANDING_VALUE > ACTIVE_EXPOSED_ORDER_VALUE + 0.01 THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- ===== FLAG CONSISTENCY =====

-- 16. IS_SUPPLIER_AT_RISK = (perf deterioration AND downstream exposure)
SELECT 'IS_SUPPLIER_AT_RISK flag consistency' AS check_name,
       SUM(CASE WHEN IS_SUPPLIER_AT_RISK !=
            (HAS_SUPPLIER_PERFORMANCE_DETERIORATION AND HAS_DOWNSTREAM_EXPOSURE) THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN IS_SUPPLIER_AT_RISK !=
            (HAS_SUPPLIER_PERFORMANCE_DETERIORATION AND HAS_DOWNSTREAM_EXPOSURE) THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 17. HAS_DOWNSTREAM_EXPOSURE = (late shipments OR outstanding orders OR low inventory)
SELECT 'HAS_DOWNSTREAM_EXPOSURE flag consistency' AS check_name,
       SUM(CASE WHEN HAS_DOWNSTREAM_EXPOSURE !=
            (HAS_LATE_SHIPMENT_EXPOSURE OR HAS_OUTSTANDING_ORDER_EXPOSURE OR HAS_LOW_INVENTORY_EXPOSURE)
            THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN HAS_DOWNSTREAM_EXPOSURE !=
            (HAS_LATE_SHIPMENT_EXPOSURE OR HAS_OUTSTANDING_ORDER_EXPOSURE OR HAS_LOW_INVENTORY_EXPOSURE)
            THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- ===== NON-NEGATIVE CHECKS =====

-- 18. All count/qty/value columns >= 0
SELECT 'All exposure metrics non-negative' AS check_name,
       SUM(CASE WHEN SUPPLIED_PART_COUNT < 0 OR EXPOSED_PLANT_COUNT < 0
                  OR EXPOSED_INVENTORY_QTY < 0 OR EXPOSED_ORDER_COUNT < 0
                  OR EXPOSED_OUTSTANDING_QTY < 0 OR EXPOSED_OUTSTANDING_VALUE < 0
                  OR EXPOSED_SHIPMENT_COUNT < 0 OR LATE_SHIPMENT_COUNT < 0
            THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN SUPPLIED_PART_COUNT < 0 OR EXPOSED_PLANT_COUNT < 0
                  OR EXPOSED_INVENTORY_QTY < 0 OR EXPOSED_ORDER_COUNT < 0
                  OR EXPOSED_OUTSTANDING_QTY < 0 OR EXPOSED_OUTSTANDING_VALUE < 0
                  OR EXPOSED_SHIPMENT_COUNT < 0 OR LATE_SHIPMENT_COUNT < 0
            THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;
