-- =============================================================================
-- MART_ORDER_FULFILLMENT — Production Validation Checks
-- Target: SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT
-- Run after V2.5.0 is applied.
-- =============================================================================

-- V2.5.0 column contract: 37 columns, 50,000 rows, grain ORDER_ID

-- =============================================================================
-- 1. STRUCTURAL CHECKS
-- =============================================================================

-- 1a. Row count
SELECT 'ROW_COUNT' AS check_name,
  COUNT(*) AS actual, 50000 AS expected,
  CASE WHEN COUNT(*) = 50000 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 1b. Column count
SELECT 'COLUMN_COUNT' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_ORDER_FULFILLMENT') AS actual,
  37 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_ORDER_FULFILLMENT') = 37
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1c. Grain uniqueness
SELECT 'GRAIN_UNIQUENESS' AS check_name,
  (SELECT COUNT(*) FROM (
    SELECT ORDER_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT
    GROUP BY ORDER_ID HAVING COUNT(*) > 1)) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM (
    SELECT ORDER_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT
    GROUP BY ORDER_ID HAVING COUNT(*) > 1)) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1d. Null PK
SELECT 'NULL_ORDER_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT WHERE ORDER_ID IS NULL) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT WHERE ORDER_ID IS NULL) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1e. Analysis date
SELECT 'ANALYSIS_AS_OF_DATE' AS check_name,
  NULL AS actual, NULL AS expected,
  CASE WHEN (SELECT COUNT(DISTINCT ANALYSIS_AS_OF_DATE) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT) = 1
       AND (SELECT MIN(ANALYSIS_AS_OF_DATE) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT) = '2026-09-30'
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 2. REFERENTIAL INTEGRITY
-- =============================================================================

-- 2a. FK: CUSTOMER_ID
SELECT 'FK_CUSTOMER_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT m
   WHERE m.CUSTOMER_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_CUSTOMER dc WHERE dc.CUSTOMER_ID = m.CUSTOMER_ID)
  ) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT m
   WHERE m.CUSTOMER_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_CUSTOMER dc WHERE dc.CUSTOMER_ID = m.CUSTOMER_ID)
  ) = 0 THEN 'PASS' ELSE 'FAIL' END AS result;

-- 2b. FK: PLANT_ID
SELECT 'FK_PLANT_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT m
   WHERE m.PLANT_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_PLANT dp WHERE dp.PLANT_ID = m.PLANT_ID)
  ) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT m
   WHERE m.PLANT_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_PLANT dp WHERE dp.PLANT_ID = m.PLANT_ID)
  ) = 0 THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 3. METRIC BOUNDS
-- =============================================================================

-- 3a. FULFILLMENT_PCT between 0 and 100
SELECT 'FULFILLMENT_PCT_BOUNDS' AS check_name,
  SUM(CASE WHEN FULFILLMENT_PCT < 0 OR FULFILLMENT_PCT > 100 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN FULFILLMENT_PCT < 0 OR FULFILLMENT_PCT > 100 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT
WHERE FULFILLMENT_PCT IS NOT NULL;

-- 3b. OUTSTANDING_QTY >= 0
SELECT 'OUTSTANDING_QTY_GE_0' AS check_name,
  SUM(CASE WHEN OUTSTANDING_QTY < 0 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN OUTSTANDING_QTY < 0 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 3c. OVER_SHIPPED_QTY >= 0
SELECT 'OVER_SHIPPED_QTY_GE_0' AS check_name,
  SUM(CASE WHEN OVER_SHIPPED_QTY < 0 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN OVER_SHIPPED_QTY < 0 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 3d. EFFECTIVE_SHIPPED_QTY <= ACTIVE_ORDERED_QTY
SELECT 'EFFECTIVE_LE_ACTIVE_ORDERED' AS check_name,
  SUM(CASE WHEN EFFECTIVE_SHIPPED_QTY > ACTIVE_ORDERED_QTY THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN EFFECTIVE_SHIPPED_QTY > ACTIVE_ORDERED_QTY THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- =============================================================================
-- 4. FLAG CONSISTENCY
-- =============================================================================

-- 4a. HAS_OVER_SHIPMENT = (OVER_SHIPPED_QTY > 0)
SELECT 'HAS_OVER_SHIPMENT_CONSISTENCY' AS check_name,
  SUM(CASE WHEN HAS_OVER_SHIPMENT != (OVER_SHIPPED_QTY > 0) THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN HAS_OVER_SHIPMENT != (OVER_SHIPPED_QTY > 0) THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 4b. FULFILLED implies OUTSTANDING_QTY = 0
SELECT 'FULFILLED_IMPLIES_OQ_ZERO' AS check_name,
  SUM(CASE WHEN IS_FULFILLED AND OUTSTANDING_QTY != 0 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN IS_FULFILLED AND OUTSTANDING_QTY != 0 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 4c. PARTIALLY_FULFILLED implies OQ > 0 AND ESQ > 0
SELECT 'PARTIAL_IMPLIES_OQ_AND_ESQ' AS check_name,
  SUM(CASE WHEN IS_PARTIALLY_FULFILLED
    AND NOT (OUTSTANDING_QTY > 0 AND EFFECTIVE_SHIPPED_QTY > 0)
  THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN IS_PARTIALLY_FULFILLED
    AND NOT (OUTSTANDING_QTY > 0 AND EFFECTIVE_SHIPPED_QTY > 0)
  THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 4d. UNFULFILLED implies OQ > 0 AND ESQ = 0
SELECT 'UNFULFILLED_IMPLIES_OQ_AND_ESQ_ZERO' AS check_name,
  SUM(CASE WHEN IS_UNFULFILLED
    AND NOT (OUTSTANDING_QTY > 0 AND EFFECTIVE_SHIPPED_QTY = 0)
  THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN IS_UNFULFILLED
    AND NOT (OUTSTANDING_QTY > 0 AND EFFECTIVE_SHIPPED_QTY = 0)
  THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 4e. CANCELLED implies all lines cancelled
SELECT 'CANCELLED_IMPLIES_ALL_LINES' AS check_name,
  SUM(CASE WHEN IS_CANCELLED AND CANCELLED_LINE_COUNT != TOTAL_ORDER_LINE_COUNT THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN IS_CANCELLED AND CANCELLED_LINE_COUNT != TOTAL_ORDER_LINE_COUNT THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 4f. Exactly one fulfillment state TRUE per row
SELECT 'EXACTLY_ONE_STATE' AS check_name,
  SUM(CASE WHEN (IS_FULFILLED::INT + IS_PARTIALLY_FULFILLED::INT + IS_UNFULFILLED::INT + IS_CANCELLED::INT) != 1
  THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN (IS_FULFILLED::INT + IS_PARTIALLY_FULFILLED::INT + IS_UNFULFILLED::INT + IS_CANCELLED::INT) != 1
  THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 4g. IS_LATE = IS_CURRENT_LATE OR IS_DELIVERED_LATE
SELECT 'IS_LATE_CONSISTENCY' AS check_name,
  SUM(CASE WHEN IS_LATE != (IS_CURRENT_LATE OR IS_DELIVERED_LATE) THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN IS_LATE != (IS_CURRENT_LATE OR IS_DELIVERED_LATE) THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 4h. IS_CURRENT_LATE / IS_DELIVERED_LATE overlap count (INFORMATIONAL — not a failure)
SELECT 'LATE_OVERLAP_COUNT' AS check_name,
  SUM(CASE WHEN IS_CURRENT_LATE AND IS_DELIVERED_LATE THEN 1 ELSE 0 END) AS overlap_count,
  'INFORMATIONAL' AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- =============================================================================
-- 5. RECONCILIATION
-- =============================================================================

-- 5a. RAW_SHIPPED_QTY reconciliation with source
-- mart RAW_SHIPPED_QTY should equal sum of FACT_SHIPMENT_LINE.SHIPPED_QTY
-- for non-cancelled order lines.
SELECT 'RAW_SHIPPED_QTY_RECONCILE' AS check_name,
  (SELECT SUM(RAW_SHIPPED_QTY) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT) AS mart_total,
  (SELECT SUM(fsl.SHIPPED_QTY)
   FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE fsl
   JOIN SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE fol ON fsl.ORDER_LINE_ID = fol.ORDER_LINE_ID
   WHERE fol.LINE_STATUS != 'CANCELLED') AS source_total,
  CASE WHEN (SELECT SUM(RAW_SHIPPED_QTY) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT) =
       (SELECT SUM(fsl.SHIPPED_QTY)
        FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE fsl
        JOIN SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE fol ON fsl.ORDER_LINE_ID = fol.ORDER_LINE_ID
        WHERE fol.LINE_STATUS != 'CANCELLED')
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 5b. ORDER_VALUE reconciliation
SELECT 'ORDER_VALUE_RECONCILE' AS check_name,
  (SELECT SUM(ORDER_VALUE) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT) AS mart_total,
  (SELECT SUM(LINE_AMOUNT) FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE) AS source_total,
  CASE WHEN (SELECT SUM(ORDER_VALUE) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT) =
       (SELECT SUM(LINE_AMOUNT) FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE)
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 6. FAN-OUT DETECTION
-- =============================================================================

-- 6a. Confirm 50,000 rows (no fan-out from dimension joins)
SELECT 'FAN_OUT_DETECTION' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT) AS actual,
  50000 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT) = 50000
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 7. CANCELLED ORDER SHIPMENT CONSISTENCY
-- =============================================================================

-- 7a. Cancelled orders must have SHIPMENT_COUNT = 0
SELECT 'CANCELLED_SHIPMENT_COUNT_ZERO' AS check_name,
  SUM(CASE WHEN IS_CANCELLED = TRUE AND SHIPMENT_COUNT != 0 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN IS_CANCELLED = TRUE AND SHIPMENT_COUNT != 0 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 7b. Cancelled orders must have LATE_SHIPMENT_COUNT = 0
SELECT 'CANCELLED_LATE_SHIPMENT_ZERO' AS check_name,
  SUM(CASE WHEN IS_CANCELLED = TRUE AND LATE_SHIPMENT_COUNT != 0 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN IS_CANCELLED = TRUE AND LATE_SHIPMENT_COUNT != 0 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 7c. Cancelled orders must have HAS_DELAYED_SHIPMENT = FALSE
SELECT 'CANCELLED_NO_DELAYED_SHIPMENT' AS check_name,
  SUM(CASE WHEN IS_CANCELLED = TRUE AND HAS_DELAYED_SHIPMENT = TRUE THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN IS_CANCELLED = TRUE AND HAS_DELAYED_SHIPMENT = TRUE THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;
