-- =============================================================================
-- MART_ORDER_FULFILLMENT — Scenario Behavioral Observations (INFORMATIONAL)
-- Target: SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT
-- Run after V2.5.0 is applied and VALIDATION.SCENARIO_AFFECTED_ENTITY is loaded.
-- =============================================================================
--
-- These queries compare scenario-affected orders against the non-scenario
-- population. All results are informational observations, NOT pass/fail.
-- No mart logic should be tuned based on these results.

-- =============================================================================
-- SC-000001 — Supplier Deterioration
-- =============================================================================
WITH sc1_orders AS (
    SELECT ENTITY_ID AS ORDER_ID
    FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY
    WHERE SCENARIO_ID = 'SC-000001' AND ENTITY_TYPE = 'ORDER'
)
SELECT
    'SC-000001' AS SCENARIO_ID,
    CASE WHEN s.ORDER_ID IS NOT NULL THEN 'SCENARIO' ELSE 'BASELINE' END AS POPULATION,
    COUNT(*) AS ORDER_COUNT,
    ROUND(AVG(m.FULFILLMENT_PCT), 2) AS AVG_FULFILLMENT_PCT,
    ROUND(100.0 * SUM(m.IS_CURRENT_LATE::INT) / COUNT(*), 2) AS CURRENT_LATE_RATE,
    ROUND(100.0 * SUM(m.IS_DELIVERED_LATE::INT) / COUNT(*), 2) AS DELIVERED_LATE_RATE,
    ROUND(100.0 * SUM(m.IS_LATE::INT) / COUNT(*), 2) AS LATE_RATE,
    ROUND(100.0 * SUM(m.IS_PARTIALLY_FULFILLED::INT) / COUNT(*), 2) AS PARTIALLY_FULFILLED_RATE,
    ROUND(100.0 * SUM(m.IS_UNFULFILLED::INT) / COUNT(*), 2) AS UNFULFILLED_RATE,
    SUM(m.OUTSTANDING_QTY) AS TOTAL_OUTSTANDING_QTY,
    ROUND(SUM(m.OUTSTANDING_VALUE), 2) AS TOTAL_OUTSTANDING_VALUE
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT m
LEFT JOIN sc1_orders s ON m.ORDER_ID = s.ORDER_ID
GROUP BY 1, 2
ORDER BY 1, 2;

-- =============================================================================
-- SC-000002 — Inventory Shortage
-- =============================================================================
WITH sc2_orders AS (
    SELECT ENTITY_ID AS ORDER_ID
    FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY
    WHERE SCENARIO_ID = 'SC-000002' AND ENTITY_TYPE = 'ORDER'
)
SELECT
    'SC-000002' AS SCENARIO_ID,
    CASE WHEN s.ORDER_ID IS NOT NULL THEN 'SCENARIO' ELSE 'BASELINE' END AS POPULATION,
    COUNT(*) AS ORDER_COUNT,
    ROUND(AVG(m.FULFILLMENT_PCT), 2) AS AVG_FULFILLMENT_PCT,
    ROUND(100.0 * SUM(m.IS_CURRENT_LATE::INT) / COUNT(*), 2) AS CURRENT_LATE_RATE,
    ROUND(100.0 * SUM(m.IS_DELIVERED_LATE::INT) / COUNT(*), 2) AS DELIVERED_LATE_RATE,
    ROUND(100.0 * SUM(m.IS_LATE::INT) / COUNT(*), 2) AS LATE_RATE,
    ROUND(100.0 * SUM(m.IS_PARTIALLY_FULFILLED::INT) / COUNT(*), 2) AS PARTIALLY_FULFILLED_RATE,
    ROUND(100.0 * SUM(m.IS_UNFULFILLED::INT) / COUNT(*), 2) AS UNFULFILLED_RATE,
    SUM(m.OUTSTANDING_QTY) AS TOTAL_OUTSTANDING_QTY,
    ROUND(SUM(m.OUTSTANDING_VALUE), 2) AS TOTAL_OUTSTANDING_VALUE
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT m
LEFT JOIN sc2_orders s ON m.ORDER_ID = s.ORDER_ID
GROUP BY 1, 2
ORDER BY 1, 2;

-- =============================================================================
-- SC-000003 — Plant Bottleneck
-- =============================================================================
WITH sc3_orders AS (
    SELECT ENTITY_ID AS ORDER_ID
    FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY
    WHERE SCENARIO_ID = 'SC-000003' AND ENTITY_TYPE = 'ORDER'
)
SELECT
    'SC-000003' AS SCENARIO_ID,
    CASE WHEN s.ORDER_ID IS NOT NULL THEN 'SCENARIO' ELSE 'BASELINE' END AS POPULATION,
    COUNT(*) AS ORDER_COUNT,
    ROUND(AVG(m.FULFILLMENT_PCT), 2) AS AVG_FULFILLMENT_PCT,
    ROUND(100.0 * SUM(m.IS_CURRENT_LATE::INT) / COUNT(*), 2) AS CURRENT_LATE_RATE,
    ROUND(100.0 * SUM(m.IS_DELIVERED_LATE::INT) / COUNT(*), 2) AS DELIVERED_LATE_RATE,
    ROUND(100.0 * SUM(m.IS_LATE::INT) / COUNT(*), 2) AS LATE_RATE,
    ROUND(100.0 * SUM(m.IS_PARTIALLY_FULFILLED::INT) / COUNT(*), 2) AS PARTIALLY_FULFILLED_RATE,
    ROUND(100.0 * SUM(m.IS_UNFULFILLED::INT) / COUNT(*), 2) AS UNFULFILLED_RATE,
    SUM(m.OUTSTANDING_QTY) AS TOTAL_OUTSTANDING_QTY,
    ROUND(SUM(m.OUTSTANDING_VALUE), 2) AS TOTAL_OUTSTANDING_VALUE
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT m
LEFT JOIN sc3_orders s ON m.ORDER_ID = s.ORDER_ID
GROUP BY 1, 2
ORDER BY 1, 2;

-- =============================================================================
-- SC-000004 — Logistics Disruption (traced from affected shipments to orders)
-- =============================================================================
WITH scenario_shipments AS (
    SELECT ENTITY_ID AS SHIPMENT_ID
    FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY
    WHERE SCENARIO_ID = 'SC-000004' AND ENTITY_TYPE = 'SHIPMENT'
),
sc4_orders AS (
    SELECT DISTINCT fol.ORDER_ID
    FROM scenario_shipments ss
    JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE fsl ON ss.SHIPMENT_ID = fsl.SHIPMENT_ID
    JOIN SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE fol ON fsl.ORDER_LINE_ID = fol.ORDER_LINE_ID
)
SELECT
    'SC-000004' AS SCENARIO_ID,
    CASE WHEN s.ORDER_ID IS NOT NULL THEN 'SCENARIO' ELSE 'BASELINE' END AS POPULATION,
    COUNT(*) AS ORDER_COUNT,
    ROUND(AVG(m.FULFILLMENT_PCT), 2) AS AVG_FULFILLMENT_PCT,
    ROUND(100.0 * SUM(m.IS_CURRENT_LATE::INT) / COUNT(*), 2) AS CURRENT_LATE_RATE,
    ROUND(100.0 * SUM(m.IS_DELIVERED_LATE::INT) / COUNT(*), 2) AS DELIVERED_LATE_RATE,
    ROUND(100.0 * SUM(m.IS_LATE::INT) / COUNT(*), 2) AS LATE_RATE,
    ROUND(100.0 * SUM(m.IS_PARTIALLY_FULFILLED::INT) / COUNT(*), 2) AS PARTIALLY_FULFILLED_RATE,
    ROUND(100.0 * SUM(m.IS_UNFULFILLED::INT) / COUNT(*), 2) AS UNFULFILLED_RATE,
    SUM(m.OUTSTANDING_QTY) AS TOTAL_OUTSTANDING_QTY,
    ROUND(SUM(m.OUTSTANDING_VALUE), 2) AS TOTAL_OUTSTANDING_VALUE
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT m
LEFT JOIN sc4_orders s ON m.ORDER_ID = s.ORDER_ID
GROUP BY 1, 2
ORDER BY 1, 2;

-- =============================================================================
-- SC-000005 — Customer Impact
-- =============================================================================
WITH sc5_orders AS (
    SELECT ENTITY_ID AS ORDER_ID
    FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY
    WHERE SCENARIO_ID = 'SC-000005' AND ENTITY_TYPE = 'ORDER'
)
SELECT
    'SC-000005' AS SCENARIO_ID,
    CASE WHEN s.ORDER_ID IS NOT NULL THEN 'SCENARIO' ELSE 'BASELINE' END AS POPULATION,
    COUNT(*) AS ORDER_COUNT,
    ROUND(AVG(m.FULFILLMENT_PCT), 2) AS AVG_FULFILLMENT_PCT,
    ROUND(100.0 * SUM(m.IS_CURRENT_LATE::INT) / COUNT(*), 2) AS CURRENT_LATE_RATE,
    ROUND(100.0 * SUM(m.IS_DELIVERED_LATE::INT) / COUNT(*), 2) AS DELIVERED_LATE_RATE,
    ROUND(100.0 * SUM(m.IS_LATE::INT) / COUNT(*), 2) AS LATE_RATE,
    ROUND(100.0 * SUM(m.IS_PARTIALLY_FULFILLED::INT) / COUNT(*), 2) AS PARTIALLY_FULFILLED_RATE,
    ROUND(100.0 * SUM(m.IS_UNFULFILLED::INT) / COUNT(*), 2) AS UNFULFILLED_RATE,
    SUM(m.OUTSTANDING_QTY) AS TOTAL_OUTSTANDING_QTY,
    ROUND(SUM(m.OUTSTANDING_VALUE), 2) AS TOTAL_OUTSTANDING_VALUE
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT m
LEFT JOIN sc5_orders s ON m.ORDER_ID = s.ORDER_ID
GROUP BY 1, 2
ORDER BY 1, 2;
