-- =============================================================================
-- MART_SUPPLIER_RISK — Production Validation Checks
-- Target: SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK
-- Run after V2.4.0 is applied.
-- =============================================================================

-- V2.4.0 column contract: 50 columns, 75 rows, grain SUPPLIER_ID

-- =============================================================================
-- 1. STRUCTURAL CHECKS
-- =============================================================================

-- 1a. Row count
SELECT 'ROW_COUNT' AS check_name,
  COUNT(*) AS actual, 75 AS expected,
  CASE WHEN COUNT(*) = 75 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 1b. Column count
SELECT 'COLUMN_COUNT' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_SUPPLIER_RISK') AS actual,
  50 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_SUPPLIER_RISK') = 50
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1c. Grain uniqueness
SELECT 'GRAIN_UNIQUENESS' AS check_name,
  (SELECT COUNT(*) FROM (
    SELECT SUPPLIER_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK
    GROUP BY SUPPLIER_ID HAVING COUNT(*) > 1)) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM (
    SELECT SUPPLIER_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK
    GROUP BY SUPPLIER_ID HAVING COUNT(*) > 1)) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1d. Null PK
SELECT 'NULL_SUPPLIER_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK WHERE SUPPLIER_ID IS NULL) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK WHERE SUPPLIER_ID IS NULL) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1e. Analysis date
SELECT 'ANALYSIS_AS_OF_DATE' AS check_name,
  NULL AS actual, NULL AS expected,
  CASE WHEN (SELECT COUNT(DISTINCT ANALYSIS_AS_OF_DATE) FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK) = 1
       AND (SELECT MIN(ANALYSIS_AS_OF_DATE) FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK) = '2026-09-30'
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 2. SEVERITY METRIC BOUNDS (V2.4.0 additions)
-- =============================================================================

-- 2a. OUTSTANDING_EXPOSURE_PCT between 0 and 100
SELECT 'OUTSTANDING_EXPOSURE_PCT_BOUNDS' AS check_name,
  SUM(CASE WHEN OUTSTANDING_EXPOSURE_PCT < 0 OR OUTSTANDING_EXPOSURE_PCT > 100 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN OUTSTANDING_EXPOSURE_PCT < 0 OR OUTSTANDING_EXPOSURE_PCT > 100 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 2b. LOW_INVENTORY_EXPOSURE_PCT between 0 and 100
SELECT 'LOW_INV_EXPOSURE_PCT_BOUNDS' AS check_name,
  SUM(CASE WHEN LOW_INVENTORY_EXPOSURE_PCT < 0 OR LOW_INVENTORY_EXPOSURE_PCT > 100 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN LOW_INVENTORY_EXPOSURE_PCT < 0 OR LOW_INVENTORY_EXPOSURE_PCT > 100 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 2c. LOW_INVENTORY_POSITION_COUNT <= EXPOSED_INVENTORY_POSITION_COUNT
SELECT 'LOW_INV_LE_TOTAL_INV' AS check_name,
  SUM(CASE WHEN LOW_INVENTORY_POSITION_COUNT > EXPOSED_INVENTORY_POSITION_COUNT THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN LOW_INVENTORY_POSITION_COUNT > EXPOSED_INVENTORY_POSITION_COUNT THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 2d. ACTIVE_EXPOSED_OUTSTANDING_VALUE <= ACTIVE_EXPOSED_ORDER_VALUE
SELECT 'ACTIVE_OUTSTANDING_LE_ACTIVE_ORDER' AS check_name,
  SUM(CASE WHEN ACTIVE_EXPOSED_OUTSTANDING_VALUE > ACTIVE_EXPOSED_ORDER_VALUE THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN ACTIVE_EXPOSED_OUTSTANDING_VALUE > ACTIVE_EXPOSED_ORDER_VALUE THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- =============================================================================
-- 3. FLAG CONSISTENCY
-- =============================================================================

-- 3a. HAS_SUPPLIER_PERFORMANCE_DETERIORATION
SELECT 'PERF_DETERIORATION_CONSISTENCY' AS check_name,
  SUM(CASE WHEN HAS_SUPPLIER_PERFORMANCE_DETERIORATION !=
    (HAS_OTD_DETERIORATION OR HAS_QUALITY_DETERIORATION OR HAS_LEAD_TIME_DETERIORATION)
  THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN HAS_SUPPLIER_PERFORMANCE_DETERIORATION !=
    (HAS_OTD_DETERIORATION OR HAS_QUALITY_DETERIORATION OR HAS_LEAD_TIME_DETERIORATION)
  THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 3b. HAS_DOWNSTREAM_EXPOSURE
SELECT 'DOWNSTREAM_EXPOSURE_CONSISTENCY' AS check_name,
  SUM(CASE WHEN HAS_DOWNSTREAM_EXPOSURE !=
    (HAS_LATE_SHIPMENT_EXPOSURE OR HAS_OUTSTANDING_ORDER_EXPOSURE OR HAS_LOW_INVENTORY_EXPOSURE)
  THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN HAS_DOWNSTREAM_EXPOSURE !=
    (HAS_LATE_SHIPMENT_EXPOSURE OR HAS_OUTSTANDING_ORDER_EXPOSURE OR HAS_LOW_INVENTORY_EXPOSURE)
  THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 3c. IS_SUPPLIER_AT_RISK
SELECT 'AT_RISK_CONSISTENCY' AS check_name,
  SUM(CASE WHEN IS_SUPPLIER_AT_RISK !=
    (HAS_SUPPLIER_PERFORMANCE_DETERIORATION AND HAS_DOWNSTREAM_EXPOSURE)
  THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN IS_SUPPLIER_AT_RISK !=
    (HAS_SUPPLIER_PERFORMANCE_DETERIORATION AND HAS_DOWNSTREAM_EXPOSURE)
  THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 3d. HAS_LOW_INVENTORY_EXPOSURE = (LOW_INVENTORY_POSITION_COUNT > 0)
SELECT 'LOW_INV_FLAG_CONSISTENCY' AS check_name,
  SUM(CASE WHEN HAS_LOW_INVENTORY_EXPOSURE != (LOW_INVENTORY_POSITION_COUNT > 0) THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN HAS_LOW_INVENTORY_EXPOSURE != (LOW_INVENTORY_POSITION_COUNT > 0) THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- =============================================================================
-- 4. PERFORMANCE COMPLETENESS
-- =============================================================================

SELECT 'PERF_NULL_CHECK' AS check_name,
  SUM(CASE WHEN LATEST_ON_TIME_DELIVERY_PCT IS NULL OR EARLIEST_ON_TIME_DELIVERY_PCT IS NULL
           OR LATEST_QUALITY_SCORE IS NULL OR EARLIEST_QUALITY_SCORE IS NULL
           OR LATEST_AVG_LEAD_TIME_DAYS IS NULL OR EARLIEST_AVG_LEAD_TIME_DAYS IS NULL
           OR LATEST_RISK_SCORE IS NULL OR EARLIEST_RISK_SCORE IS NULL
           OR MEASUREMENT_PERIOD_COUNT IS NULL THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN LATEST_ON_TIME_DELIVERY_PCT IS NULL OR EARLIEST_ON_TIME_DELIVERY_PCT IS NULL
           OR LATEST_QUALITY_SCORE IS NULL OR EARLIEST_QUALITY_SCORE IS NULL
           OR LATEST_AVG_LEAD_TIME_DAYS IS NULL OR EARLIEST_AVG_LEAD_TIME_DAYS IS NULL
           OR LATEST_RISK_SCORE IS NULL OR EARLIEST_RISK_SCORE IS NULL
           OR MEASUREMENT_PERIOD_COUNT IS NULL THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- =============================================================================
-- 5. METRIC SANITY
-- =============================================================================

-- 5a. OUTSTANDING_QTY non-negative
SELECT 'OUTSTANDING_QTY_GE_0' AS check_name,
  SUM(CASE WHEN EXPOSED_OUTSTANDING_QTY < 0 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN EXPOSED_OUTSTANDING_QTY < 0 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- 5b. LATE_SHIPMENT_PCT bounds
SELECT 'LATE_SHIPMENT_PCT_BOUNDS' AS check_name,
  SUM(CASE WHEN LATE_SHIPMENT_PCT > 100 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN LATE_SHIPMENT_PCT > 100 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK;

-- =============================================================================
-- 6. SCENARIO 1 (SC-000001) VALIDATION — SEPARATE
-- Run only after VALIDATION.SCENARIO_AFFECTED_ENTITY is loaded.
-- =============================================================================

-- 6a. SUP-000062 flags
SELECT 'SC1_SUP062_FLAGS' AS check_name,
  CASE WHEN IS_SUPPLIER_AT_RISK = TRUE
       AND HAS_SUPPLIER_PERFORMANCE_DETERIORATION = TRUE
       AND HAS_OTD_DETERIORATION = TRUE
       AND HAS_DOWNSTREAM_EXPOSURE = TRUE
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_SUPPLIER_RISK
WHERE SUPPLIER_ID = 'SUP-000062';

-- 6b. Part coverage (ID-set comparison)
SELECT 'SC1_PARTS' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY
   WHERE SCENARIO_ID = 'SC-000001' AND ENTITY_TYPE = 'PART') AS gt_count,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART
   WHERE SUPPLIER_ID = 'SUP-000062' AND ACTIVE_FLAG = TRUE) AS mart_count,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY gt
   JOIN SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART bsp
     ON gt.ENTITY_ID = bsp.PART_ID AND bsp.SUPPLIER_ID = 'SUP-000062' AND bsp.ACTIVE_FLAG = TRUE
   WHERE gt.SCENARIO_ID = 'SC-000001' AND gt.ENTITY_TYPE = 'PART') AS matched;

-- 6c. Plant coverage
SELECT 'SC1_PLANTS' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY
   WHERE SCENARIO_ID = 'SC-000001' AND ENTITY_TYPE = 'PLANT') AS gt_count,
  (SELECT COUNT(DISTINCT inv.PLANT_ID)
   FROM SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART bsp
   JOIN SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT inv ON bsp.PART_ID = inv.PART_ID
   WHERE bsp.SUPPLIER_ID = 'SUP-000062' AND bsp.ACTIVE_FLAG = TRUE) AS mart_count,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY gt
   WHERE gt.SCENARIO_ID = 'SC-000001' AND gt.ENTITY_TYPE = 'PLANT'
     AND EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART bsp
                 JOIN SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT inv ON bsp.PART_ID = inv.PART_ID
                 WHERE bsp.SUPPLIER_ID = 'SUP-000062' AND bsp.ACTIVE_FLAG = TRUE
                   AND inv.PLANT_ID = gt.ENTITY_ID)) AS matched;

-- 6d. Shipment coverage
SELECT 'SC1_SHIPMENTS' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY
   WHERE SCENARIO_ID = 'SC-000001' AND ENTITY_TYPE = 'SHIPMENT') AS gt_count,
  (SELECT COUNT(DISTINCT sl.SHIPMENT_ID)
   FROM SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART bsp
   JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE sl ON bsp.PART_ID = sl.PART_ID
   WHERE bsp.SUPPLIER_ID = 'SUP-000062' AND bsp.ACTIVE_FLAG = TRUE) AS mart_count,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY gt
   WHERE gt.SCENARIO_ID = 'SC-000001' AND gt.ENTITY_TYPE = 'SHIPMENT'
     AND EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART bsp
                 JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE sl ON bsp.PART_ID = sl.PART_ID
                 WHERE bsp.SUPPLIER_ID = 'SUP-000062' AND bsp.ACTIVE_FLAG = TRUE
                   AND sl.SHIPMENT_ID = gt.ENTITY_ID)) AS matched;

-- 6e. Order coverage
SELECT 'SC1_ORDERS' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY
   WHERE SCENARIO_ID = 'SC-000001' AND ENTITY_TYPE = 'ORDER') AS gt_count,
  (SELECT COUNT(DISTINCT ol.ORDER_ID)
   FROM SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART bsp
   JOIN SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE ol ON bsp.PART_ID = ol.PART_ID
   WHERE bsp.SUPPLIER_ID = 'SUP-000062' AND bsp.ACTIVE_FLAG = TRUE
     AND ol.LINE_STATUS != 'CANCELLED') AS mart_count,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.VALIDATION.SCENARIO_AFFECTED_ENTITY gt
   WHERE gt.SCENARIO_ID = 'SC-000001' AND gt.ENTITY_TYPE = 'ORDER'
     AND EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART bsp
                 JOIN SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE ol ON bsp.PART_ID = ol.PART_ID
                 WHERE bsp.SUPPLIER_ID = 'SUP-000062' AND bsp.ACTIVE_FLAG = TRUE
                   AND ol.LINE_STATUS != 'CANCELLED'
                   AND ol.ORDER_ID = gt.ENTITY_ID)) AS matched;
