-- =============================================================================
-- MART_ORDER_FULFILLMENT Validation Checks
-- Data-relative: no fixed row counts; validates against current Silver state.
-- =============================================================================

-- ===== STRUCTURAL CHECKS =====

-- 1. Column count = 37
SELECT 'Column count = 37' AS check_name,
       COUNT(*) AS val,
       CASE WHEN COUNT(*) = 37 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_ORDER_FULFILLMENT'
  AND TABLE_CATALOG = 'SUPPLY_CHAIN_DW';

-- 2. Row count = distinct ORDER_ID in FACT_ORDER_LINE
SELECT 'Row count = distinct orders in Silver' AS check_name,
       (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT) AS mart_rows,
       (SELECT COUNT(DISTINCT ORDER_ID) FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE) AS silver_orders,
       CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT)
                 = (SELECT COUNT(DISTINCT ORDER_ID) FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE)
            THEN 'PASS' ELSE 'FAIL' END AS result;

-- 3. Grain uniqueness: one row per ORDER_ID
SELECT 'Grain uniqueness (ORDER_ID)' AS check_name,
       COUNT(*) - COUNT(DISTINCT ORDER_ID) AS duplicates,
       CASE WHEN COUNT(*) = COUNT(DISTINCT ORDER_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 4. No NULL ORDER_ID
SELECT 'No NULL ORDER_ID' AS check_name,
       SUM(CASE WHEN ORDER_ID IS NULL THEN 1 ELSE 0 END) AS null_count,
       CASE WHEN SUM(CASE WHEN ORDER_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- ===== SCENARIO S3: PLANT BOTTLENECK (PLT-000003) =====

-- 5. PLT-000003 orders exist
SELECT 'PLT-000003 orders exist' AS check_name,
       COUNT(*) AS order_count,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT
WHERE PLANT_ID = 'PLT-000003';

-- 6. PLT-000003 has non-fulfilled orders (UNFULFILLED or PARTIALLY_FULFILLED)
SELECT 'PLT-000003 backlog visible' AS check_name,
       SUM(CASE WHEN FULFILLMENT_STATE IN ('UNFULFILLED','PARTIALLY_FULFILLED') THEN 1 ELSE 0 END) AS backlog_count,
       CASE WHEN SUM(CASE WHEN FULFILLMENT_STATE IN ('UNFULFILLED','PARTIALLY_FULFILLED') THEN 1 ELSE 0 END) > 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT
WHERE PLANT_ID = 'PLT-000003';

-- ===== FAN-OUT DETECTION =====

-- 7. No fan-out
SELECT 'No fan-out (grain)' AS check_name,
       COUNT(*) AS duplicates,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM (
    SELECT ORDER_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT
    GROUP BY ORDER_ID HAVING COUNT(*) > 1
);

-- ===== QUANTITY RECONCILIATION =====

-- 8. Total ORDERED_QTY matches Silver
SELECT 'ORDERED_QTY reconciles to Silver' AS check_name,
       (SELECT SUM(ORDERED_QTY) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT) AS mart_total,
       (SELECT SUM(ORDERED_QTY) FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE) AS silver_total,
       CASE WHEN ABS((SELECT SUM(ORDERED_QTY) FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT)
                   - (SELECT SUM(ORDERED_QTY) FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE)) < 0.01
            THEN 'PASS' ELSE 'FAIL' END AS result;

-- 9. EFFECTIVE_SHIPPED_QTY <= ACTIVE_ORDERED_QTY per order (capping works)
SELECT 'Shipped <= Ordered per order' AS check_name,
       SUM(CASE WHEN EFFECTIVE_SHIPPED_QTY > ACTIVE_ORDERED_QTY + 0.01 THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN EFFECTIVE_SHIPPED_QTY > ACTIVE_ORDERED_QTY + 0.01 THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 10. OUTSTANDING_QTY = ACTIVE_ORDERED_QTY - EFFECTIVE_SHIPPED_QTY (non-cancelled)
SELECT 'Outstanding qty formula' AS check_name,
       SUM(CASE WHEN ABS(OUTSTANDING_QTY - (ACTIVE_ORDERED_QTY - EFFECTIVE_SHIPPED_QTY)) > 0.01
                 AND FULFILLMENT_STATE != 'CANCELLED' THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN ABS(OUTSTANDING_QTY - (ACTIVE_ORDERED_QTY - EFFECTIVE_SHIPPED_QTY)) > 0.01
                 AND FULFILLMENT_STATE != 'CANCELLED' THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 11. ACTIVE_LINE_COUNT = TOTAL - CANCELLED
SELECT 'Active line count formula' AS check_name,
       SUM(CASE WHEN ACTIVE_LINE_COUNT != TOTAL_ORDER_LINE_COUNT - CANCELLED_LINE_COUNT THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN ACTIVE_LINE_COUNT != TOTAL_ORDER_LINE_COUNT - CANCELLED_LINE_COUNT THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- ===== FULFILLMENT PCT BOUNDS =====

-- 12. FULFILLMENT_PCT between 0 and 100 (or NULL for all-cancelled)
SELECT 'FULFILLMENT_PCT [0,100]' AS check_name,
       SUM(CASE WHEN FULFILLMENT_PCT IS NOT NULL AND (FULFILLMENT_PCT < 0 OR FULFILLMENT_PCT > 100) THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN FULFILLMENT_PCT IS NOT NULL AND (FULFILLMENT_PCT < 0 OR FULFILLMENT_PCT > 100) THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- ===== FLAG CONSISTENCY =====

-- 13. FULFILLMENT_STATE matches boolean flags
SELECT 'Fulfillment state flag consistency' AS check_name,
       SUM(CASE WHEN IS_FULFILLED != (FULFILLMENT_STATE = 'FULFILLED')
                  OR IS_PARTIALLY_FULFILLED != (FULFILLMENT_STATE = 'PARTIALLY_FULFILLED')
                  OR IS_UNFULFILLED != (FULFILLMENT_STATE = 'UNFULFILLED')
                  OR IS_CANCELLED != (FULFILLMENT_STATE = 'CANCELLED') THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN IS_FULFILLED != (FULFILLMENT_STATE = 'FULFILLED')
                  OR IS_PARTIALLY_FULFILLED != (FULFILLMENT_STATE = 'PARTIALLY_FULFILLED')
                  OR IS_UNFULFILLED != (FULFILLMENT_STATE = 'UNFULFILLED')
                  OR IS_CANCELLED != (FULFILLMENT_STATE = 'CANCELLED') THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 14. IS_LATE = IS_CURRENT_LATE OR IS_DELIVERED_LATE
SELECT 'IS_LATE flag consistency' AS check_name,
       SUM(CASE WHEN IS_LATE != (IS_CURRENT_LATE OR IS_DELIVERED_LATE) THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN IS_LATE != (IS_CURRENT_LATE OR IS_DELIVERED_LATE) THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- 15. CANCELLED orders have all lines cancelled
SELECT 'Cancelled order consistency' AS check_name,
       SUM(CASE WHEN IS_CANCELLED AND CANCELLED_LINE_COUNT != TOTAL_ORDER_LINE_COUNT THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN IS_CANCELLED AND CANCELLED_LINE_COUNT != TOTAL_ORDER_LINE_COUNT THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- ===== LATE DELIVERY RECONCILIATION =====

-- 16. LATE_SHIPMENT_COUNT bounded by SHIPMENT_COUNT per order
SELECT 'Late shipments <= total shipments' AS check_name,
       SUM(CASE WHEN LATE_SHIPMENT_COUNT > SHIPMENT_COUNT THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN LATE_SHIPMENT_COUNT > SHIPMENT_COUNT THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

-- ===== NON-NEGATIVE CHECKS =====

-- 17. All qty/value/count columns non-negative
SELECT 'All metrics non-negative' AS check_name,
       SUM(CASE WHEN ORDERED_QTY < 0 OR ACTIVE_ORDERED_QTY < 0 OR EFFECTIVE_SHIPPED_QTY < 0
                  OR OUTSTANDING_QTY < 0 OR OVER_SHIPPED_QTY < 0
                  OR ORDER_VALUE < 0 OR OUTSTANDING_VALUE < 0
                  OR SHIPMENT_COUNT < 0 OR LATE_SHIPMENT_COUNT < 0
            THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN ORDERED_QTY < 0 OR ACTIVE_ORDERED_QTY < 0 OR EFFECTIVE_SHIPPED_QTY < 0
                  OR OUTSTANDING_QTY < 0 OR OVER_SHIPPED_QTY < 0
                  OR ORDER_VALUE < 0 OR OUTSTANDING_VALUE < 0
                  OR SHIPMENT_COUNT < 0 OR LATE_SHIPMENT_COUNT < 0
            THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;
