-- =============================================================================
-- MART_CUSTOMER_IMPACT Validation Checks
-- Data-relative: no fixed row counts; validates against current Silver state.
-- =============================================================================

-- ===== STRUCTURAL CHECKS =====

-- 1. Column count = 34
SELECT 'Column count = 34' AS check_name,
       COUNT(*) AS val,
       CASE WHEN COUNT(*) = 34 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_CUSTOMER_IMPACT'
  AND TABLE_CATALOG = 'SUPPLY_CHAIN_DW';

-- 2. Row count = distinct CUSTOMER_ID in FACT_ORDER_LINE
SELECT 'Row count = customers with orders' AS check_name,
       (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT) AS mart_rows,
       (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE) AS silver_customers,
       CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT)
                 = (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE)
            THEN 'PASS' ELSE 'FAIL' END AS result;

-- 3. Grain uniqueness
SELECT 'Grain uniqueness (CUSTOMER_ID)' AS check_name,
       COUNT(*) - COUNT(DISTINCT CUSTOMER_ID) AS duplicates,
       CASE WHEN COUNT(*) = COUNT(DISTINCT CUSTOMER_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;

-- 4. No NULL CUSTOMER_ID
SELECT 'No NULL CUSTOMER_ID' AS check_name,
       SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS null_count,
       CASE WHEN SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;

-- ===== FAN-OUT DETECTION =====

-- 5. No fan-out
SELECT 'No fan-out (grain)' AS check_name,
       COUNT(*) AS duplicates,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM (
    SELECT CUSTOMER_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT
    GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1
);

-- ===== ORDER COUNT RECONCILIATION =====

-- 6. Total order count across all customers = distinct orders in Silver
SELECT 'Total orders reconcile to Silver' AS check_name,
       (SELECT SUM(TOTAL_ORDER_COUNT) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT) AS mart_total,
       (SELECT COUNT(DISTINCT ORDER_ID) FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE) AS silver_orders,
       CASE WHEN (SELECT SUM(TOTAL_ORDER_COUNT) FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT)
                 = (SELECT COUNT(DISTINCT ORDER_ID) FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE)
            THEN 'PASS' ELSE 'FAIL' END AS result;

-- 7. Order state counts sum to total per customer
SELECT 'Order states sum to total' AS check_name,
       SUM(CASE WHEN FULFILLED_ORDER_COUNT + PARTIALLY_FULFILLED_ORDER_COUNT
                     + UNFULFILLED_ORDER_COUNT + CANCELLED_ORDER_COUNT != TOTAL_ORDER_COUNT
                THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN FULFILLED_ORDER_COUNT + PARTIALLY_FULFILLED_ORDER_COUNT
                     + UNFULFILLED_ORDER_COUNT + CANCELLED_ORDER_COUNT != TOTAL_ORDER_COUNT
                THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;

-- ===== BOUNDED COUNTS =====

-- 8. Late order counts bounded by total
SELECT 'Late orders <= total orders' AS check_name,
       SUM(CASE WHEN TOTAL_LATE_ORDER_COUNT > TOTAL_ORDER_COUNT THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN TOTAL_LATE_ORDER_COUNT > TOTAL_ORDER_COUNT THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;

-- 9. Late shipments bounded by total shipments
SELECT 'Late shipments <= total shipments' AS check_name,
       SUM(CASE WHEN LATE_SHIPMENT_COUNT > TOTAL_SHIPMENT_COUNT THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN LATE_SHIPMENT_COUNT > TOTAL_SHIPMENT_COUNT THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;

-- ===== VALUE / QTY CHECKS =====

-- 10. Outstanding value non-negative
SELECT 'Outstanding value non-negative' AS check_name,
       SUM(CASE WHEN OUTSTANDING_VALUE < 0 THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN OUTSTANDING_VALUE < 0 THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;

-- 11. Outstanding qty non-negative
SELECT 'Outstanding qty non-negative' AS check_name,
       SUM(CASE WHEN OUTSTANDING_QTY < 0 THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN OUTSTANDING_QTY < 0 THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;

-- 12. FULFILLMENT_PCT between 0 and 100 (or NULL)
SELECT 'FULFILLMENT_PCT [0,100]' AS check_name,
       SUM(CASE WHEN FULFILLMENT_PCT IS NOT NULL AND (FULFILLMENT_PCT < 0 OR FULFILLMENT_PCT > 100) THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN FULFILLMENT_PCT IS NOT NULL AND (FULFILLMENT_PCT < 0 OR FULFILLMENT_PCT > 100) THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;

-- ===== FLAG CONSISTENCY =====

-- 13. IS_IMPACTED flag
SELECT 'IS_IMPACTED flag consistency' AS check_name,
       SUM(CASE WHEN IS_IMPACTED !=
            (HAS_LATE_ORDER OR HAS_PARTIAL_FULFILLMENT OR HAS_UNFULFILLED_ORDER OR HAS_DELAYED_SHIPMENT)
            THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN IS_IMPACTED !=
            (HAS_LATE_ORDER OR HAS_PARTIAL_FULFILLMENT OR HAS_UNFULFILLED_ORDER OR HAS_DELAYED_SHIPMENT)
            THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;

-- 14. HAS_LATE_ORDER = (TOTAL_LATE_ORDER_COUNT > 0)
SELECT 'HAS_LATE_ORDER flag' AS check_name,
       SUM(CASE WHEN HAS_LATE_ORDER != (TOTAL_LATE_ORDER_COUNT > 0) THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN HAS_LATE_ORDER != (TOTAL_LATE_ORDER_COUNT > 0) THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;

-- ===== ALL COUNTS NON-NEGATIVE =====

-- 15. All count/qty columns non-negative
SELECT 'All metrics non-negative' AS check_name,
       SUM(CASE WHEN TOTAL_ORDER_COUNT < 0 OR OPEN_ORDER_COUNT < 0 OR FULFILLED_ORDER_COUNT < 0
                  OR PARTIALLY_FULFILLED_ORDER_COUNT < 0 OR UNFULFILLED_ORDER_COUNT < 0
                  OR CANCELLED_ORDER_COUNT < 0 OR ACTIVE_ORDERED_QTY < 0
                  OR ACTIVE_SHIPPED_QTY < 0 OR TOTAL_SHIPMENT_COUNT < 0
            THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN TOTAL_ORDER_COUNT < 0 OR OPEN_ORDER_COUNT < 0 OR FULFILLED_ORDER_COUNT < 0
                  OR PARTIALLY_FULFILLED_ORDER_COUNT < 0 OR UNFULFILLED_ORDER_COUNT < 0
                  OR CANCELLED_ORDER_COUNT < 0 OR ACTIVE_ORDERED_QTY < 0
                  OR ACTIVE_SHIPPED_QTY < 0 OR TOTAL_SHIPMENT_COUNT < 0
            THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_CUSTOMER_IMPACT;
