-- =============================================================================
-- MART_LOGISTICS_PERFORMANCE Validation Checks
-- Data-relative: no fixed row counts; validates against current Silver state.
-- =============================================================================

-- ===== STRUCTURAL CHECKS =====

-- 1. Column count = 29
SELECT 'Column count = 29' AS check_name,
       COUNT(*) AS val,
       CASE WHEN COUNT(*) = 29 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_LOGISTICS_PERFORMANCE'
  AND TABLE_CATALOG = 'SUPPLY_CHAIN_DW';

-- 2. Row count = FACT_SHIPMENT
SELECT 'Row count = FACT_SHIPMENT' AS check_name,
       (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE) AS mart_rows,
       (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT) AS silver_rows,
       CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE)
                 = (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT)
            THEN 'PASS' ELSE 'FAIL' END AS result;

-- 3. Grain uniqueness: one row per SHIPMENT_ID
SELECT 'Grain uniqueness (SHIPMENT_ID)' AS check_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT SHIPMENT_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT SHIPMENT_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- 4. No NULL SHIPMENT_ID
SELECT 'No NULL SHIPMENT_ID' AS check_name,
       SUM(CASE WHEN SHIPMENT_ID IS NULL THEN 1 ELSE 0 END) AS null_count,
       CASE WHEN SUM(CASE WHEN SHIPMENT_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- ===== SCENARIO S4: LOGISTICS DISRUPTION (RTE-000036) =====

-- 5. RTE-000036 shipments exist in mart
SELECT 'RTE-000036 shipments exist' AS check_name,
       COUNT(*) AS shipments_on_route,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE
WHERE ROUTE_ID = 'RTE-000036';

-- 6. RTE-000036 has delayed shipments
SELECT 'RTE-000036 has delayed shipments' AS check_name,
       SUM(CASE WHEN SHIPMENT_STATUS = 'DELAYED' THEN 1 ELSE 0 END) AS delayed_count,
       CASE WHEN SUM(CASE WHEN SHIPMENT_STATUS = 'DELAYED' THEN 1 ELSE 0 END) > 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE
WHERE ROUTE_ID = 'RTE-000036';

-- 7. DELAY_REPORTED events present for RTE-000036
SELECT 'RTE-000036 has DELAY_REPORTED events' AS check_name,
       SUM(DELAY_REPORTED_EVENT_COUNT) AS total_delay_events,
       CASE WHEN SUM(DELAY_REPORTED_EVENT_COUNT) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE
WHERE ROUTE_ID = 'RTE-000036';

-- 8. ROUTE_DEVIATION events present for RTE-000036
SELECT 'RTE-000036 has ROUTE_DEVIATION events' AS check_name,
       SUM(ROUTE_DEVIATION_EVENT_COUNT) AS total_deviation_events,
       CASE WHEN SUM(ROUTE_DEVIATION_EVENT_COUNT) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE
WHERE ROUTE_ID = 'RTE-000036';

-- ===== FAN-OUT DETECTION =====

-- 9. No fan-out: duplicate SHIPMENT_ID check
SELECT 'No fan-out (grain)' AS check_name,
       COUNT(*) AS duplicates,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM (
    SELECT SHIPMENT_ID
    FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE
    GROUP BY SHIPMENT_ID
    HAVING COUNT(*) > 1
);

-- ===== TRANSIT / DELAY METRIC RECONCILIATION =====

-- 10. IS_ON_TIME matches Silver exactly
SELECT 'IS_ON_TIME matches Silver' AS check_name,
       SUM(CASE WHEN COALESCE(m.IS_ON_TIME::VARCHAR, 'NULL') != COALESCE(s.IS_ON_TIME::VARCHAR, 'NULL') THEN 1 ELSE 0 END) AS mismatches,
       CASE WHEN SUM(CASE WHEN COALESCE(m.IS_ON_TIME::VARCHAR, 'NULL') != COALESCE(s.IS_ON_TIME::VARCHAR, 'NULL') THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE m
JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT s ON m.SHIPMENT_ID = s.SHIPMENT_ID;

-- 11. PLANNED_TRANSIT_HOURS matches Silver
SELECT 'PLANNED_TRANSIT_HOURS matches Silver' AS check_name,
       SUM(CASE WHEN COALESCE(m.PLANNED_TRANSIT_HOURS, -1) != COALESCE(s.PLANNED_TRANSIT_HOURS, -1) THEN 1 ELSE 0 END) AS mismatches,
       CASE WHEN SUM(CASE WHEN COALESCE(m.PLANNED_TRANSIT_HOURS, -1) != COALESCE(s.PLANNED_TRANSIT_HOURS, -1) THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE m
JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT s ON m.SHIPMENT_ID = s.SHIPMENT_ID;

-- 12. ACTUAL_TRANSIT_HOURS matches Silver
SELECT 'ACTUAL_TRANSIT_HOURS matches Silver' AS check_name,
       SUM(CASE WHEN COALESCE(m.ACTUAL_TRANSIT_HOURS, -1) != COALESCE(s.ACTUAL_TRANSIT_HOURS, -1) THEN 1 ELSE 0 END) AS mismatches,
       CASE WHEN SUM(CASE WHEN COALESCE(m.ACTUAL_TRANSIT_HOURS, -1) != COALESCE(s.ACTUAL_TRANSIT_HOURS, -1) THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE m
JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT s ON m.SHIPMENT_ID = s.SHIPMENT_ID;

-- 13. TRANSIT_VARIANCE_HOURS = ACTUAL - PLANNED (when both non-null)
SELECT 'TRANSIT_VARIANCE formula' AS check_name,
       SUM(CASE WHEN ACTUAL_TRANSIT_HOURS IS NOT NULL AND PLANNED_TRANSIT_HOURS IS NOT NULL
                 AND TRANSIT_VARIANCE_HOURS != ACTUAL_TRANSIT_HOURS - PLANNED_TRANSIT_HOURS THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN ACTUAL_TRANSIT_HOURS IS NOT NULL AND PLANNED_TRANSIT_HOURS IS NOT NULL
                 AND TRANSIT_VARIANCE_HOURS != ACTUAL_TRANSIT_HOURS - PLANNED_TRANSIT_HOURS THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- 14. TRANSIT_VARIANCE_HOURS is NULL when either transit is NULL
SELECT 'TRANSIT_VARIANCE NULL consistency' AS check_name,
       SUM(CASE WHEN (ACTUAL_TRANSIT_HOURS IS NULL OR PLANNED_TRANSIT_HOURS IS NULL)
                 AND TRANSIT_VARIANCE_HOURS IS NOT NULL THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN (ACTUAL_TRANSIT_HOURS IS NULL OR PLANNED_TRANSIT_HOURS IS NULL)
                 AND TRANSIT_VARIANCE_HOURS IS NOT NULL THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- ===== COST AND METRIC BOUNDS =====

-- 15. SHIPPING_COST non-negative
SELECT 'SHIPPING_COST non-negative' AS check_name,
       SUM(CASE WHEN SHIPPING_COST < 0 THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN SHIPPING_COST < 0 THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- 16. Event counts non-negative
SELECT 'Event counts non-negative' AS check_name,
       SUM(CASE WHEN ROUTE_DEVIATION_EVENT_COUNT < 0 OR DELAY_REPORTED_EVENT_COUNT < 0 THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN ROUTE_DEVIATION_EVENT_COUNT < 0 OR DELAY_REPORTED_EVENT_COUNT < 0 THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- 17. DISTINCT_ORDER_COUNT non-negative
SELECT 'DISTINCT_ORDER_COUNT non-negative' AS check_name,
       SUM(CASE WHEN DISTINCT_ORDER_COUNT < 0 THEN 1 ELSE 0 END) AS violations,
       CASE WHEN SUM(CASE WHEN DISTINCT_ORDER_COUNT < 0 THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE;

-- 18. SHIPPING_COST reconciles to Silver
SELECT 'SHIPPING_COST matches Silver' AS check_name,
       SUM(CASE WHEN COALESCE(m.SHIPPING_COST, -1) != COALESCE(s.SHIPPING_COST, -1) THEN 1 ELSE 0 END) AS mismatches,
       CASE WHEN SUM(CASE WHEN COALESCE(m.SHIPPING_COST, -1) != COALESCE(s.SHIPPING_COST, -1) THEN 1 ELSE 0 END) = 0
            THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_LOGISTICS_PERFORMANCE m
JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT s ON m.SHIPMENT_ID = s.SHIPMENT_ID;
