-- =============================================================================
-- MART_INVENTORY_RISK — Production Validation Checks
-- Target: SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK
-- Run after V2.7.0 is applied.
-- =============================================================================

-- V2.7.0 column contract: 24 columns, 2,250 rows, grain PLANT_ID + PART_ID

-- =============================================================================
-- 1. STRUCTURAL CHECKS
-- =============================================================================

-- 1a. Row count
SELECT 'ROW_COUNT' AS check_name,
  COUNT(*) AS actual, 2250 AS expected,
  CASE WHEN COUNT(*) = 2250 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK;

-- 1b. Column count
SELECT 'COLUMN_COUNT' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_INVENTORY_RISK') AS actual,
  24 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME = 'MART_INVENTORY_RISK') = 24
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1c. Grain uniqueness
SELECT 'GRAIN_UNIQUENESS' AS check_name,
  (SELECT COUNT(*) FROM (
    SELECT PLANT_ID, PART_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK
    GROUP BY PLANT_ID, PART_ID HAVING COUNT(*) > 1)) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM (
    SELECT PLANT_ID, PART_ID FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK
    GROUP BY PLANT_ID, PART_ID HAVING COUNT(*) > 1)) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1d. Null PLANT_ID
SELECT 'NULL_PLANT_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK WHERE PLANT_ID IS NULL) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK WHERE PLANT_ID IS NULL) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1e. Null PART_ID
SELECT 'NULL_PART_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK WHERE PART_ID IS NULL) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK WHERE PART_ID IS NULL) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 1f. Analysis date
SELECT 'ANALYSIS_AS_OF_DATE' AS check_name,
  NULL AS actual, NULL AS expected,
  CASE WHEN (SELECT COUNT(DISTINCT ANALYSIS_AS_OF_DATE) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK) = 1
       AND (SELECT MIN(ANALYSIS_AS_OF_DATE) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK) = '2026-09-30'
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 2. REFERENTIAL INTEGRITY
-- =============================================================================

-- 2a. FK: PLANT_ID
SELECT 'FK_PLANT_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK m
   WHERE m.PLANT_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_PLANT dp WHERE dp.PLANT_ID = m.PLANT_ID)
  ) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK m
   WHERE m.PLANT_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_PLANT dp WHERE dp.PLANT_ID = m.PLANT_ID)
  ) = 0 THEN 'PASS' ELSE 'FAIL' END AS result;

-- 2b. FK: PART_ID
SELECT 'FK_PART_ID' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK m
   WHERE m.PART_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_PART dpt WHERE dpt.PART_ID = m.PART_ID)
  ) AS actual,
  0 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK m
   WHERE m.PART_ID IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.DIM_PART dpt WHERE dpt.PART_ID = m.PART_ID)
  ) = 0 THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 3. SOURCE PRESERVATION
-- =============================================================================

-- 3a. NEEDS_REORDER count
SELECT 'NEEDS_REORDER_PRESERVATION' AS check_name,
  (SELECT SUM(CASE WHEN NEEDS_REORDER THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK) AS mart_count,
  (SELECT SUM(CASE WHEN NEEDS_REORDER THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT) AS source_count,
  CASE WHEN (SELECT SUM(CASE WHEN NEEDS_REORDER THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK) =
       (SELECT SUM(CASE WHEN NEEDS_REORDER THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT)
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 3b. BELOW_SAFETY_STOCK count
SELECT 'BELOW_SAFETY_PRESERVATION' AS check_name,
  (SELECT SUM(CASE WHEN BELOW_SAFETY_STOCK THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK) AS mart_count,
  (SELECT SUM(CASE WHEN BELOW_SAFETY_STOCK THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT) AS source_count,
  CASE WHEN (SELECT SUM(CASE WHEN BELOW_SAFETY_STOCK THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK) =
       (SELECT SUM(CASE WHEN BELOW_SAFETY_STOCK THEN 1 ELSE 0 END) FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT)
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- 3c. ON_HAND_QTY reconciliation
SELECT 'ON_HAND_QTY_RECONCILE' AS check_name,
  (SELECT SUM(ON_HAND_QTY) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK) AS mart_total,
  (SELECT SUM(ON_HAND_QTY) FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT) AS source_total,
  CASE WHEN (SELECT SUM(ON_HAND_QTY) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK) =
       (SELECT SUM(ON_HAND_QTY) FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT)
  THEN 'PASS' ELSE 'FAIL' END AS result;

-- =============================================================================
-- 4. FORMULA CONSISTENCY
-- =============================================================================

-- 4a. NEEDS_REORDER = (AVAILABLE_QTY <= REORDER_POINT)
SELECT 'NEEDS_REORDER_CONSISTENCY' AS check_name,
  SUM(CASE WHEN NEEDS_REORDER != (AVAILABLE_QTY <= REORDER_POINT) THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN NEEDS_REORDER != (AVAILABLE_QTY <= REORDER_POINT) THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK;

-- 4b. BELOW_SAFETY_STOCK = (AVAILABLE_QTY <= SAFETY_STOCK)
SELECT 'BELOW_SAFETY_CONSISTENCY' AS check_name,
  SUM(CASE WHEN BELOW_SAFETY_STOCK != (AVAILABLE_QTY <= SAFETY_STOCK) THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN BELOW_SAFETY_STOCK != (AVAILABLE_QTY <= SAFETY_STOCK) THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK;

-- 4c. SHORTAGE_QTY = GREATEST(REORDER_POINT - AVAILABLE_QTY, 0)
SELECT 'SHORTAGE_QTY_FORMULA' AS check_name,
  SUM(CASE WHEN SHORTAGE_QTY != GREATEST(REORDER_POINT - AVAILABLE_QTY, 0) THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN SHORTAGE_QTY != GREATEST(REORDER_POINT - AVAILABLE_QTY, 0) THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK;

-- 4d. BELOW_SAFETY_STOCK_QTY = GREATEST(SAFETY_STOCK - AVAILABLE_QTY, 0)
SELECT 'BELOW_SAFETY_QTY_FORMULA' AS check_name,
  SUM(CASE WHEN BELOW_SAFETY_STOCK_QTY != GREATEST(SAFETY_STOCK - AVAILABLE_QTY, 0) THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN BELOW_SAFETY_STOCK_QTY != GREATEST(SAFETY_STOCK - AVAILABLE_QTY, 0) THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK;

-- 4e. IS_OUT_OF_STOCK = (AVAILABLE_QTY = 0)
SELECT 'IS_OUT_OF_STOCK_CONSISTENCY' AS check_name,
  SUM(CASE WHEN IS_OUT_OF_STOCK != (AVAILABLE_QTY = 0) THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN IS_OUT_OF_STOCK != (AVAILABLE_QTY = 0) THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK;

-- =============================================================================
-- 5. NON-NEGATIVE QUANTITY CHECKS
-- =============================================================================

-- 5a. BELOW_SAFETY_STOCK_QTY >= 0
SELECT 'BELOW_SAFETY_QTY_GE_0' AS check_name,
  SUM(CASE WHEN BELOW_SAFETY_STOCK_QTY < 0 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN BELOW_SAFETY_STOCK_QTY < 0 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK;

-- 5b. SHORTAGE_QTY >= 0
SELECT 'SHORTAGE_QTY_GE_0' AS check_name,
  SUM(CASE WHEN SHORTAGE_QTY < 0 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN SHORTAGE_QTY < 0 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK;

-- 5c. ACTIVE_SUPPLIER_COUNT >= 0
SELECT 'ACTIVE_SUPPLIER_COUNT_GE_0' AS check_name,
  SUM(CASE WHEN ACTIVE_SUPPLIER_COUNT < 0 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN ACTIVE_SUPPLIER_COUNT < 0 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK;

-- 5d. OUTSTANDING_ORDER_QTY >= 0
SELECT 'OUTSTANDING_ORDER_QTY_GE_0' AS check_name,
  SUM(CASE WHEN OUTSTANDING_ORDER_QTY < 0 THEN 1 ELSE 0 END) AS actual,
  0 AS expected,
  CASE WHEN SUM(CASE WHEN OUTSTANDING_ORDER_QTY < 0 THEN 1 ELSE 0 END) = 0
  THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK;

-- =============================================================================
-- 6. FAN-OUT DETECTION
-- =============================================================================

SELECT 'FAN_OUT_DETECTION' AS check_name,
  (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK) AS actual,
  2250 AS expected,
  CASE WHEN (SELECT COUNT(*) FROM SUPPLY_CHAIN_DW.GOLD.MART_INVENTORY_RISK) = 2250
  THEN 'PASS' ELSE 'FAIL' END AS result;
