-- =============================================================================
-- Incremental INSERT: FACT_SHIPMENT_EVENT
-- Silver target: SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT
-- RAW source: SUPPLY_CHAIN_DW.RAW.SHIPMENT_EVENTS
-- Grain: SHIPMENT_EVENT_ID
-- Strategy: Append-only — INSERT new rows not already in Silver
-- Derived: EVENT_DATE_KEY = EVENT_TIMESTAMP::DATE
-- =============================================================================
-- Parameter: $BATCH_ID (set via: SET BATCH_ID = 'INCR_...';)

INSERT INTO SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT
  (SHIPMENT_EVENT_ID, SHIPMENT_ID, EVENT_TIMESTAMP, EVENT_DATE_KEY,
   EVENT_TYPE, LOCATION_LATITUDE, LOCATION_LONGITUDE, EVENT_DESCRIPTION)
SELECT
  src.SHIPMENT_EVENT_ID, src.SHIPMENT_ID, src.EVENT_TIMESTAMP,
  src.EVENT_TIMESTAMP::DATE AS EVENT_DATE_KEY,
  src.EVENT_TYPE, src.LOCATION_LATITUDE, src.LOCATION_LONGITUDE,
  src.EVENT_DESCRIPTION
FROM SUPPLY_CHAIN_DW.RAW.SHIPMENT_EVENTS src
WHERE src.LOAD_BATCH_ID = $BATCH_ID
  AND NOT EXISTS (
    SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT tgt
    WHERE tgt.SHIPMENT_EVENT_ID = src.SHIPMENT_EVENT_ID
  );
