-- =============================================================================
-- Incremental INSERT: FACT_VEHICLE_TELEMETRY
-- Silver target: SUPPLY_CHAIN_DW.SILVER.FACT_VEHICLE_TELEMETRY
-- RAW source: SUPPLY_CHAIN_DW.RAW.VEHICLE_TELEMETRY
-- Grain: TELEMETRY_ID
-- Strategy: Append-only — INSERT new rows not already in Silver
-- Derived: EVENT_DATE_KEY = EVENT_TIMESTAMP::DATE
-- =============================================================================
-- Parameter: $BATCH_ID (set via: SET BATCH_ID = 'INCR_...';)

INSERT INTO SUPPLY_CHAIN_DW.SILVER.FACT_VEHICLE_TELEMETRY
  (TELEMETRY_ID, VEHICLE_ID, SHIPMENT_ID, EVENT_TIMESTAMP, EVENT_DATE_KEY,
   LATITUDE, LONGITUDE, SPEED_KMPH, VEHICLE_STATUS, DISTANCE_TRAVELLED_KM)
SELECT
  src.TELEMETRY_ID, src.VEHICLE_ID, src.SHIPMENT_ID, src.EVENT_TIMESTAMP,
  src.EVENT_TIMESTAMP::DATE AS EVENT_DATE_KEY,
  src.LATITUDE, src.LONGITUDE, src.SPEED_KMPH,
  src.VEHICLE_STATUS, src.DISTANCE_TRAVELLED_KM
FROM SUPPLY_CHAIN_DW.RAW.VEHICLE_TELEMETRY src
WHERE src.LOAD_BATCH_ID = $BATCH_ID
  AND NOT EXISTS (
    SELECT 1 FROM SUPPLY_CHAIN_DW.SILVER.FACT_VEHICLE_TELEMETRY tgt
    WHERE tgt.TELEMETRY_ID = src.TELEMETRY_ID
  );
