-- =============================================================================
-- Incremental MERGE: FACT_INVENTORY_SNAPSHOT
-- Silver target: SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT
-- RAW source: SUPPLY_CHAIN_DW.RAW.INVENTORY
-- Grain: PLANT_ID + PART_ID
-- Strategy: Identify affected keys from batch, recompute from ALL RAW
-- =============================================================================
-- Parameter: $BATCH_ID (set via: SET BATCH_ID = 'INCR_...';)

MERGE INTO SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT AS tgt
USING (
  WITH
  affected_keys AS (
    SELECT DISTINCT PLANT_ID, PART_ID
    FROM SUPPLY_CHAIN_DW.RAW.INVENTORY
    WHERE LOAD_BATCH_ID = $BATCH_ID
  ),
  inventory_dedup AS (
    SELECT * FROM (
      SELECT *,
        ROW_NUMBER() OVER (PARTITION BY PLANT_ID, PART_ID ORDER BY LAST_UPDATED_AT DESC) AS rn
      FROM SUPPLY_CHAIN_DW.RAW.INVENTORY
      WHERE (PLANT_ID, PART_ID) IN (SELECT PLANT_ID, PART_ID FROM affected_keys)
    ) WHERE rn = 1
  )
  SELECT
    PLANT_ID, PART_ID, ON_HAND_QTY, RESERVED_QTY, AVAILABLE_QTY,
    SAFETY_STOCK, REORDER_POINT, INVENTORY_STATUS,
    CASE WHEN AVAILABLE_QTY <= REORDER_POINT THEN TRUE ELSE FALSE END AS NEEDS_REORDER,
    CASE WHEN AVAILABLE_QTY <= SAFETY_STOCK THEN TRUE ELSE FALSE END AS BELOW_SAFETY_STOCK,
    LAST_UPDATED_AT,
    LAST_UPDATED_AT::DATE AS SNAPSHOT_DATE_KEY
  FROM inventory_dedup
) AS src
ON tgt.PLANT_ID = src.PLANT_ID AND tgt.PART_ID = src.PART_ID
WHEN MATCHED AND src.LAST_UPDATED_AT > tgt.LAST_UPDATED_AT
  THEN UPDATE SET
    tgt.ON_HAND_QTY        = src.ON_HAND_QTY,
    tgt.RESERVED_QTY       = src.RESERVED_QTY,
    tgt.AVAILABLE_QTY      = src.AVAILABLE_QTY,
    tgt.SAFETY_STOCK       = src.SAFETY_STOCK,
    tgt.REORDER_POINT      = src.REORDER_POINT,
    tgt.INVENTORY_STATUS   = src.INVENTORY_STATUS,
    tgt.NEEDS_REORDER      = src.NEEDS_REORDER,
    tgt.BELOW_SAFETY_STOCK = src.BELOW_SAFETY_STOCK,
    tgt.LAST_UPDATED_AT    = src.LAST_UPDATED_AT,
    tgt.SNAPSHOT_DATE_KEY  = src.SNAPSHOT_DATE_KEY
WHEN NOT MATCHED
  THEN INSERT (PLANT_ID, PART_ID, ON_HAND_QTY, RESERVED_QTY, AVAILABLE_QTY,
               SAFETY_STOCK, REORDER_POINT, INVENTORY_STATUS,
               NEEDS_REORDER, BELOW_SAFETY_STOCK, LAST_UPDATED_AT, SNAPSHOT_DATE_KEY)
  VALUES (src.PLANT_ID, src.PART_ID, src.ON_HAND_QTY, src.RESERVED_QTY, src.AVAILABLE_QTY,
          src.SAFETY_STOCK, src.REORDER_POINT, src.INVENTORY_STATUS,
          src.NEEDS_REORDER, src.BELOW_SAFETY_STOCK, src.LAST_UPDATED_AT, src.SNAPSHOT_DATE_KEY);
