-- =============================================================================
-- Incremental MERGE: FACT_SHIPMENT
-- Silver target: SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT
-- RAW source: SUPPLY_CHAIN_DW.RAW.SHIPMENTS
-- Grain: SHIPMENT_ID
-- Strategy: Identify affected keys from batch, recompute from ALL RAW
-- =============================================================================
-- Parameter: $BATCH_ID (set via: SET BATCH_ID = 'INCR_...';)

MERGE INTO SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT AS tgt
USING (
  WITH
  affected_keys AS (
    SELECT DISTINCT SHIPMENT_ID
    FROM SUPPLY_CHAIN_DW.RAW.SHIPMENTS
    WHERE LOAD_BATCH_ID = $BATCH_ID
  ),
  shipments_dedup AS (
    SELECT * FROM (
      SELECT *,
        ROW_NUMBER() OVER (PARTITION BY SHIPMENT_ID ORDER BY LAST_UPDATED_AT DESC) AS rn
      FROM SUPPLY_CHAIN_DW.RAW.SHIPMENTS
      WHERE SHIPMENT_ID IN (SELECT SHIPMENT_ID FROM affected_keys)
    ) WHERE rn = 1
  )
  SELECT
    SHIPMENT_ID, SHIPMENT_TYPE, CARRIER_ID, ROUTE_ID, SHIPMENT_STATUS,
    PLANNED_DEPARTURE_AT, ACTUAL_DEPARTURE_AT, PLANNED_DELIVERY_AT, ACTUAL_DELIVERY_AT,
    PLANNED_DEPARTURE_AT::DATE             AS DEPARTURE_DATE_KEY,
    PLANNED_DELIVERY_AT::DATE              AS DELIVERY_DATE_KEY,
    SHIPPING_COST,
    DATEDIFF('HOUR', ACTUAL_DEPARTURE_AT, ACTUAL_DELIVERY_AT) AS ACTUAL_TRANSIT_HOURS,
    DATEDIFF('HOUR', PLANNED_DEPARTURE_AT, PLANNED_DELIVERY_AT) AS PLANNED_TRANSIT_HOURS,
    CASE
      WHEN ACTUAL_DELIVERY_AT IS NULL THEN NULL
      WHEN ACTUAL_DELIVERY_AT <= PLANNED_DELIVERY_AT THEN TRUE
      ELSE FALSE
    END AS IS_ON_TIME,
    LAST_UPDATED_AT
  FROM shipments_dedup
) AS src
ON tgt.SHIPMENT_ID = src.SHIPMENT_ID
WHEN MATCHED AND src.LAST_UPDATED_AT > tgt.LAST_UPDATED_AT
  THEN UPDATE SET
    tgt.SHIPMENT_TYPE        = src.SHIPMENT_TYPE,
    tgt.CARRIER_ID           = src.CARRIER_ID,
    tgt.ROUTE_ID             = src.ROUTE_ID,
    tgt.SHIPMENT_STATUS      = src.SHIPMENT_STATUS,
    tgt.PLANNED_DEPARTURE_AT = src.PLANNED_DEPARTURE_AT,
    tgt.ACTUAL_DEPARTURE_AT  = src.ACTUAL_DEPARTURE_AT,
    tgt.PLANNED_DELIVERY_AT  = src.PLANNED_DELIVERY_AT,
    tgt.ACTUAL_DELIVERY_AT   = src.ACTUAL_DELIVERY_AT,
    tgt.DEPARTURE_DATE_KEY   = src.DEPARTURE_DATE_KEY,
    tgt.DELIVERY_DATE_KEY    = src.DELIVERY_DATE_KEY,
    tgt.SHIPPING_COST        = src.SHIPPING_COST,
    tgt.ACTUAL_TRANSIT_HOURS = src.ACTUAL_TRANSIT_HOURS,
    tgt.PLANNED_TRANSIT_HOURS = src.PLANNED_TRANSIT_HOURS,
    tgt.IS_ON_TIME           = src.IS_ON_TIME,
    tgt.LAST_UPDATED_AT      = src.LAST_UPDATED_AT
WHEN NOT MATCHED
  THEN INSERT (SHIPMENT_ID, SHIPMENT_TYPE, CARRIER_ID, ROUTE_ID, SHIPMENT_STATUS,
               PLANNED_DEPARTURE_AT, ACTUAL_DEPARTURE_AT, PLANNED_DELIVERY_AT,
               ACTUAL_DELIVERY_AT, DEPARTURE_DATE_KEY, DELIVERY_DATE_KEY,
               SHIPPING_COST, ACTUAL_TRANSIT_HOURS, PLANNED_TRANSIT_HOURS,
               IS_ON_TIME, LAST_UPDATED_AT)
  VALUES (src.SHIPMENT_ID, src.SHIPMENT_TYPE, src.CARRIER_ID, src.ROUTE_ID, src.SHIPMENT_STATUS,
          src.PLANNED_DEPARTURE_AT, src.ACTUAL_DEPARTURE_AT, src.PLANNED_DELIVERY_AT,
          src.ACTUAL_DELIVERY_AT, src.DEPARTURE_DATE_KEY, src.DELIVERY_DATE_KEY,
          src.SHIPPING_COST, src.ACTUAL_TRANSIT_HOURS, src.PLANNED_TRANSIT_HOURS,
          src.IS_ON_TIME, src.LAST_UPDATED_AT);
