-- =============================================================================
-- Incremental MERGE: FACT_SUPPLIER_PERFORMANCE
-- Silver target: SUPPLY_CHAIN_DW.SILVER.FACT_SUPPLIER_PERFORMANCE
-- RAW source: SUPPLY_CHAIN_DW.RAW.SUPPLIER_PERFORMANCE
-- Grain: SUPPLIER_ID + MEASUREMENT_DATE_KEY
-- Strategy: Identify affected keys from batch, recompute from ALL RAW
-- =============================================================================
-- Parameter: $BATCH_ID (set via: SET BATCH_ID = 'INCR_...';)

MERGE INTO SUPPLY_CHAIN_DW.SILVER.FACT_SUPPLIER_PERFORMANCE AS tgt
USING (
  WITH
  affected_keys AS (
    SELECT DISTINCT SUPPLIER_ID, MEASUREMENT_DATE
    FROM SUPPLY_CHAIN_DW.RAW.SUPPLIER_PERFORMANCE
    WHERE LOAD_BATCH_ID = $BATCH_ID
  ),
  sp_dedup AS (
    SELECT * FROM (
      SELECT *,
        ROW_NUMBER() OVER (PARTITION BY SUPPLIER_ID, MEASUREMENT_DATE ORDER BY LAST_UPDATED_AT DESC) AS rn
      FROM SUPPLY_CHAIN_DW.RAW.SUPPLIER_PERFORMANCE
      WHERE (SUPPLIER_ID, MEASUREMENT_DATE) IN (SELECT SUPPLIER_ID, MEASUREMENT_DATE FROM affected_keys)
    ) WHERE rn = 1
  )
  SELECT
    SUPPLIER_PERFORMANCE_ID, SUPPLIER_ID,
    MEASUREMENT_DATE AS MEASUREMENT_DATE_KEY,
    AVG_LEAD_TIME_DAYS, ON_TIME_DELIVERY_PCT, QUALITY_SCORE,
    FILL_RATE_PCT, RISK_SCORE, LAST_UPDATED_AT
  FROM sp_dedup
) AS src
ON tgt.SUPPLIER_ID = src.SUPPLIER_ID AND tgt.MEASUREMENT_DATE_KEY = src.MEASUREMENT_DATE_KEY
WHEN MATCHED AND src.LAST_UPDATED_AT > tgt.LAST_UPDATED_AT
  THEN UPDATE SET
    tgt.SUPPLIER_PERFORMANCE_ID = src.SUPPLIER_PERFORMANCE_ID,
    tgt.AVG_LEAD_TIME_DAYS      = src.AVG_LEAD_TIME_DAYS,
    tgt.ON_TIME_DELIVERY_PCT    = src.ON_TIME_DELIVERY_PCT,
    tgt.QUALITY_SCORE           = src.QUALITY_SCORE,
    tgt.FILL_RATE_PCT           = src.FILL_RATE_PCT,
    tgt.RISK_SCORE              = src.RISK_SCORE,
    tgt.LAST_UPDATED_AT         = src.LAST_UPDATED_AT
WHEN NOT MATCHED
  THEN INSERT (SUPPLIER_PERFORMANCE_ID, SUPPLIER_ID, MEASUREMENT_DATE_KEY,
               AVG_LEAD_TIME_DAYS, ON_TIME_DELIVERY_PCT, QUALITY_SCORE,
               FILL_RATE_PCT, RISK_SCORE, LAST_UPDATED_AT)
  VALUES (src.SUPPLIER_PERFORMANCE_ID, src.SUPPLIER_ID, src.MEASUREMENT_DATE_KEY,
          src.AVG_LEAD_TIME_DAYS, src.ON_TIME_DELIVERY_PCT, src.QUALITY_SCORE,
          src.FILL_RATE_PCT, src.RISK_SCORE, src.LAST_UPDATED_AT);
