-- =============================================================================
-- Incremental MERGE: BRIDGE_SUPPLIER_PART
-- Silver target: SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART
-- RAW source: SUPPLY_CHAIN_DW.RAW.SUPPLIER_PARTS
-- Grain: SUPPLIER_ID + PART_ID
-- Strategy: Identify affected keys from batch, recompute from ALL RAW
-- =============================================================================
-- Parameter: $BATCH_ID (set via: SET BATCH_ID = 'INCR_...';)

MERGE INTO SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART AS tgt
USING (
  WITH
  affected_keys AS (
    SELECT DISTINCT SUPPLIER_ID, PART_ID
    FROM SUPPLY_CHAIN_DW.RAW.SUPPLIER_PARTS
    WHERE LOAD_BATCH_ID = $BATCH_ID
  ),
  dedup AS (
    SELECT *,
      ROW_NUMBER() OVER (PARTITION BY SUPPLIER_ID, PART_ID ORDER BY LAST_UPDATED_AT DESC) AS rn
    FROM SUPPLY_CHAIN_DW.RAW.SUPPLIER_PARTS
    WHERE (SUPPLIER_ID, PART_ID) IN (SELECT SUPPLIER_ID, PART_ID FROM affected_keys)
  )
  SELECT
    SUPPLIER_ID, PART_ID, SUPPLIER_UNIT_COST, BASE_LEAD_TIME_DAYS,
    MINIMUM_ORDER_QTY, PREFERRED_SUPPLIER_FLAG, ACTIVE_FLAG, LAST_UPDATED_AT
  FROM dedup WHERE rn = 1
) AS src
ON tgt.SUPPLIER_ID = src.SUPPLIER_ID AND tgt.PART_ID = src.PART_ID
WHEN MATCHED AND src.LAST_UPDATED_AT > tgt.LAST_UPDATED_AT
  THEN UPDATE SET
    tgt.SUPPLIER_UNIT_COST      = src.SUPPLIER_UNIT_COST,
    tgt.BASE_LEAD_TIME_DAYS     = src.BASE_LEAD_TIME_DAYS,
    tgt.MINIMUM_ORDER_QTY       = src.MINIMUM_ORDER_QTY,
    tgt.PREFERRED_SUPPLIER_FLAG = src.PREFERRED_SUPPLIER_FLAG,
    tgt.ACTIVE_FLAG             = src.ACTIVE_FLAG,
    tgt.LAST_UPDATED_AT         = src.LAST_UPDATED_AT
WHEN NOT MATCHED
  THEN INSERT (SUPPLIER_ID, PART_ID, SUPPLIER_UNIT_COST, BASE_LEAD_TIME_DAYS,
               MINIMUM_ORDER_QTY, PREFERRED_SUPPLIER_FLAG, ACTIVE_FLAG, LAST_UPDATED_AT)
  VALUES (src.SUPPLIER_ID, src.PART_ID, src.SUPPLIER_UNIT_COST, src.BASE_LEAD_TIME_DAYS,
          src.MINIMUM_ORDER_QTY, src.PREFERRED_SUPPLIER_FLAG, src.ACTIVE_FLAG, src.LAST_UPDATED_AT);
