USE DATABASE SUPPLY_CHAIN_DW;
USE SCHEMA RAW;

CREATE STREAM IF NOT EXISTS STRM_RAW_ORDERS
ON TABLE ORDERS
APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_RAW_ORDER_LINES
ON TABLE ORDER_LINES
APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_RAW_INVENTORY
ON TABLE INVENTORY
APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_RAW_SUPPLIER_PARTS
ON TABLE SUPPLIER_PARTS
APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_RAW_SUPPLIER_PERFORMANCE
ON TABLE SUPPLIER_PERFORMANCE
APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_RAW_SHIPMENTS
ON TABLE SHIPMENTS
APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_RAW_SHIPMENT_LINES
ON TABLE SHIPMENT_LINES
APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_RAW_SHIPMENT_EVENTS
ON TABLE SHIPMENT_EVENTS
APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_RAW_VEHICLE_TELEMETRY
ON TABLE VEHICLE_TELEMETRY
APPEND_ONLY = TRUE;