USE DATABASE SUPPLY_CHAIN_DW;
USE SCHEMA CONTROL;

CREATE TABLE IF NOT EXISTS CDC_STREAM_RUN_LOG (
    RUN_ID              VARCHAR         NOT NULL,
    PIPELINE_NAME       VARCHAR         NOT NULL,
    SOURCE_TABLE        VARCHAR         NOT NULL,
    TARGET_TABLE        VARCHAR         NOT NULL,

    STARTED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT        TIMESTAMP_NTZ,

    ROWS_CAPTURED       NUMBER          DEFAULT 0,
    ROWS_INSERTED       NUMBER          DEFAULT 0,
    ROWS_UPDATED        NUMBER          DEFAULT 0,
    ROWS_SKIPPED        NUMBER          DEFAULT 0,

    STATUS              VARCHAR         NOT NULL,
    ERROR_MESSAGE       VARCHAR,

    LOAD_BATCH_IDS      VARCHAR,

    CONSTRAINT PK_CDC_STREAM_RUN_LOG
        PRIMARY KEY (RUN_ID)
);