-- =============================================================================
-- FACT_SUPPLIER_PERFORMANCE
-- Target: SUPPLY_CHAIN_DW.SILVER.FACT_SUPPLIER_PERFORMANCE
-- Source: SUPPLY_CHAIN_RAW_DATASET.RAW.SUPPLIER_PERFORMANCE
-- Grain:  One row per supplier + measurement date (SUPPLIER_ID, MEASUREMENT_DATE)
-- Dedup:  By (SUPPLIER_ID, MEASUREMENT_DATE) using LAST_UPDATED_AT DESC
-- Recovered: Exact CTAS from query history (2026-09-30 00:32:25)
-- =============================================================================

CREATE OR REPLACE TABLE SUPPLY_CHAIN_DW.SILVER.FACT_SUPPLIER_PERFORMANCE AS
WITH sp_dedup AS (
  SELECT *
  FROM (
    SELECT *,
      ROW_NUMBER() OVER (PARTITION BY SUPPLIER_ID, MEASUREMENT_DATE ORDER BY LAST_UPDATED_AT DESC) AS rn
    FROM SUPPLY_CHAIN_RAW_DATASET.RAW.SUPPLIER_PERFORMANCE
  )
  WHERE rn = 1
)
SELECT
  SUPPLIER_PERFORMANCE_ID,
  SUPPLIER_ID,
  MEASUREMENT_DATE                       AS MEASUREMENT_DATE_KEY,
  AVG_LEAD_TIME_DAYS,
  ON_TIME_DELIVERY_PCT,
  QUALITY_SCORE,
  FILL_RATE_PCT,
  RISK_SCORE,
  LAST_UPDATED_AT
FROM sp_dedup;
