-- =============================================================================
-- FACT_SHIPMENT
-- Target: SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT
-- Source: SUPPLY_CHAIN_RAW_DATASET.RAW.SHIPMENTS
-- Grain:  One row per shipment (SHIPMENT_ID)
-- Dedup:  SHIPMENTS by SHIPMENT_ID using LAST_UPDATED_AT DESC
-- Derived:
--   DEPARTURE_DATE_KEY  = PLANNED_DEPARTURE_AT::DATE
--   DELIVERY_DATE_KEY   = PLANNED_DELIVERY_AT::DATE
--   ACTUAL_TRANSIT_HOURS  = DATEDIFF(HOUR, ACTUAL_DEPARTURE_AT, ACTUAL_DELIVERY_AT)
--   PLANNED_TRANSIT_HOURS = DATEDIFF(HOUR, PLANNED_DEPARTURE_AT, PLANNED_DELIVERY_AT)
--   IS_ON_TIME = NULL-safe: NULL when not delivered, TRUE/FALSE otherwise
-- Recovered: Exact CTAS from query history (2026-09-30 00:31:07)
-- =============================================================================

CREATE OR REPLACE TABLE SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT AS
WITH shipments_dedup AS (
  SELECT *
  FROM (
    SELECT *,
      ROW_NUMBER() OVER (PARTITION BY SHIPMENT_ID ORDER BY LAST_UPDATED_AT DESC) AS rn
    FROM SUPPLY_CHAIN_RAW_DATASET.RAW.SHIPMENTS
  )
  WHERE rn = 1
)
SELECT
  SHIPMENT_ID,
  SHIPMENT_TYPE,
  CARRIER_ID,
  ROUTE_ID,
  SHIPMENT_STATUS,
  PLANNED_DEPARTURE_AT,
  ACTUAL_DEPARTURE_AT,
  PLANNED_DELIVERY_AT,
  ACTUAL_DELIVERY_AT,
  PLANNED_DEPARTURE_AT::DATE             AS DEPARTURE_DATE_KEY,
  PLANNED_DELIVERY_AT::DATE              AS DELIVERY_DATE_KEY,
  SHIPPING_COST,
  DATEDIFF('HOUR', ACTUAL_DEPARTURE_AT, ACTUAL_DELIVERY_AT) AS ACTUAL_TRANSIT_HOURS,
  DATEDIFF('HOUR', PLANNED_DEPARTURE_AT, PLANNED_DELIVERY_AT) AS PLANNED_TRANSIT_HOURS,
  CASE
    WHEN ACTUAL_DELIVERY_AT IS NULL THEN NULL
    WHEN ACTUAL_DELIVERY_AT <= PLANNED_DELIVERY_AT THEN TRUE
    ELSE FALSE
  END                                     AS IS_ON_TIME,
  LAST_UPDATED_AT
FROM shipments_dedup;
