-- =============================================================================
-- FACT_INVENTORY_SNAPSHOT
-- Target: SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT
-- Source: SUPPLY_CHAIN_DW.RAW.INVENTORY
-- Grain:  One row per plant + part (PLANT_ID, PART_ID)
-- Dedup:  INVENTORY by (PLANT_ID, PART_ID) using LAST_UPDATED_AT DESC
-- Derived:
--   NEEDS_REORDER    = AVAILABLE_QTY <= REORDER_POINT
--   BELOW_SAFETY_STOCK = AVAILABLE_QTY <= SAFETY_STOCK
--   SNAPSHOT_DATE_KEY  = LAST_UPDATED_AT::DATE
-- Recovered: Exact CTAS from query history (2026-09-30 00:32:05)
-- =============================================================================

CREATE OR REPLACE TABLE SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT AS
WITH inventory_dedup AS (
  SELECT *
  FROM (
    SELECT *,
      ROW_NUMBER() OVER (PARTITION BY PLANT_ID, PART_ID ORDER BY LAST_UPDATED_AT DESC) AS rn
    FROM SUPPLY_CHAIN_DW.RAW.INVENTORY
  )
  WHERE rn = 1
)
SELECT
  PLANT_ID,
  PART_ID,
  ON_HAND_QTY,
  RESERVED_QTY,
  AVAILABLE_QTY,
  SAFETY_STOCK,
  REORDER_POINT,
  INVENTORY_STATUS,
  CASE WHEN AVAILABLE_QTY <= REORDER_POINT THEN TRUE ELSE FALSE END AS NEEDS_REORDER,
  CASE WHEN AVAILABLE_QTY <= SAFETY_STOCK THEN TRUE ELSE FALSE END AS BELOW_SAFETY_STOCK,
  LAST_UPDATED_AT,
  LAST_UPDATED_AT::DATE                  AS SNAPSHOT_DATE_KEY
FROM inventory_dedup;
