-- Historical baseline: BRIDGE_SUPPLIER_PART
-- Source: SUPPLY_CHAIN_DW.RAW.SUPPLIER_PARTS
-- Grain: SUPPLIER_ID + PART_ID
-- Dedup: (SUPPLIER_ID, PART_ID) by LAST_UPDATED_AT DESC

INSERT INTO SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART
  (SUPPLIER_ID, PART_ID, SUPPLIER_UNIT_COST, BASE_LEAD_TIME_DAYS,
   MINIMUM_ORDER_QTY, PREFERRED_SUPPLIER_FLAG, ACTIVE_FLAG, LAST_UPDATED_AT)
WITH dedup AS (
  SELECT *,
    ROW_NUMBER() OVER (PARTITION BY SUPPLIER_ID, PART_ID ORDER BY LAST_UPDATED_AT DESC) AS rn
  FROM SUPPLY_CHAIN_DW.RAW.SUPPLIER_PARTS
)
SELECT
  SUPPLIER_ID,
  PART_ID,
  SUPPLIER_UNIT_COST,
  BASE_LEAD_TIME_DAYS,
  MINIMUM_ORDER_QTY,
  PREFERRED_SUPPLIER_FLAG,
  ACTIVE_FLAG,
  LAST_UPDATED_AT
FROM dedup
WHERE rn = 1;
