-- Historical baseline: DIM_SUPPLIER
-- Source: SUPPLY_CHAIN_DW.RAW.SUPPLIERS
-- Grain: SUPPLIER_ID

INSERT INTO SUPPLY_CHAIN_DW.SILVER.DIM_SUPPLIER
  (SUPPLIER_ID, SUPPLIER_NAME, CITY, STATE, COUNTRY,
   SUPPLIER_TIER, SUPPLIER_STATUS, CREATED_AT)
SELECT
  SUPPLIER_ID, SUPPLIER_NAME, CITY, STATE, COUNTRY,
  SUPPLIER_TIER, SUPPLIER_STATUS, CREATED_AT
FROM SUPPLY_CHAIN_DW.RAW.SUPPLIERS;
