-- Historical baseline: DIM_PART
-- Source: SUPPLY_CHAIN_DW.RAW.PARTS
-- Grain: PART_ID

INSERT INTO SUPPLY_CHAIN_DW.SILVER.DIM_PART
  (PART_ID, PART_NAME, PART_CATEGORY, UNIT_OF_MEASURE,
   STANDARD_COST, CRITICALITY, CREATED_AT)
SELECT
  PART_ID, PART_NAME, PART_CATEGORY, UNIT_OF_MEASURE,
  STANDARD_COST, CRITICALITY, CREATED_AT
FROM SUPPLY_CHAIN_DW.RAW.PARTS;
