-- Historical baseline: DIM_CUSTOMER
-- Source: SUPPLY_CHAIN_DW.RAW.CUSTOMERS
-- Grain: CUSTOMER_ID

INSERT INTO SUPPLY_CHAIN_DW.SILVER.DIM_CUSTOMER
  (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_SEGMENT, CITY, STATE,
   COUNTRY, LATITUDE, LONGITUDE, CREATED_AT)
SELECT
  CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_SEGMENT, CITY, STATE,
  COUNTRY, LATITUDE, LONGITUDE, CREATED_AT
FROM SUPPLY_CHAIN_DW.RAW.CUSTOMERS;
