-- Historical baseline: DIM_PLANT
-- Source: SUPPLY_CHAIN_DW.RAW.PLANTS
-- Grain: PLANT_ID

INSERT INTO SUPPLY_CHAIN_DW.SILVER.DIM_PLANT
  (PLANT_ID, PLANT_NAME, CITY, STATE, COUNTRY,
   LATITUDE, LONGITUDE, CAPACITY_UNITS, CREATED_AT)
SELECT
  PLANT_ID, PLANT_NAME, CITY, STATE, COUNTRY,
  LATITUDE, LONGITUDE, CAPACITY_UNITS, CREATED_AT
FROM SUPPLY_CHAIN_DW.RAW.PLANTS;
