-- Historical baseline: DIM_CARRIER
-- Source: SUPPLY_CHAIN_DW.RAW.CARRIERS
-- Grain: CARRIER_ID

INSERT INTO SUPPLY_CHAIN_DW.SILVER.DIM_CARRIER
  (CARRIER_ID, CARRIER_NAME, CARRIER_TYPE, SERVICE_LEVEL,
   BASE_COST_PER_KM, ACTIVE_FLAG, CREATED_AT)
SELECT
  CARRIER_ID, CARRIER_NAME, CARRIER_TYPE, SERVICE_LEVEL,
  BASE_COST_PER_KM, ACTIVE_FLAG, CREATED_AT
FROM SUPPLY_CHAIN_DW.RAW.CARRIERS;
