-- Historical baseline: DIM_ROUTE
-- Source: SUPPLY_CHAIN_DW.RAW.ROUTES
-- Grain: ROUTE_ID

INSERT INTO SUPPLY_CHAIN_DW.SILVER.DIM_ROUTE
  (ROUTE_ID, ORIGIN_TYPE, ORIGIN_ID, DESTINATION_TYPE, DESTINATION_ID,
   DISTANCE_KM, EXPECTED_TRANSIT_HOURS, ROUTE_RISK_LEVEL, CREATED_AT)
SELECT
  ROUTE_ID, ORIGIN_TYPE, ORIGIN_ID, DESTINATION_TYPE, DESTINATION_ID,
  DISTANCE_KM, EXPECTED_TRANSIT_HOURS, ROUTE_RISK_LEVEL, CREATED_AT
FROM SUPPLY_CHAIN_DW.RAW.ROUTES;
