-- Historical baseline: DIM_DATE
-- Source: Generated date spine (no RAW dependency)
-- Grain: DATE_KEY

INSERT INTO SUPPLY_CHAIN_DW.SILVER.DIM_DATE
  (DATE_KEY, YEAR, QUARTER, MONTH, MONTH_NAME, WEEK_OF_YEAR,
   DAY_OF_WEEK, DAY_NAME, DAY_OF_MONTH, DAY_OF_YEAR,
   IS_WEEKEND, YEAR_QUARTER, YEAR_MONTH)
WITH date_spine AS (
  SELECT DATEADD(DAY, SEQ4(), '2025-01-01'::DATE) AS DATE_KEY
  FROM TABLE(GENERATOR(ROWCOUNT => 731))
)
SELECT
  DATE_KEY,
  YEAR(DATE_KEY),
  QUARTER(DATE_KEY),
  MONTH(DATE_KEY),
  MONTHNAME(DATE_KEY),
  WEEKOFYEAR(DATE_KEY),
  DAYOFWEEK(DATE_KEY),
  DAYNAME(DATE_KEY),
  DAY(DATE_KEY),
  DAYOFYEAR(DATE_KEY),
  CASE WHEN DAYOFWEEK(DATE_KEY) IN (0,6) THEN TRUE ELSE FALSE END,
  YEAR(DATE_KEY) || '-Q' || QUARTER(DATE_KEY),
  TO_CHAR(DATE_KEY, 'YYYY-MM')
FROM date_spine
WHERE DATE_KEY <= '2026-12-31';
