-- Historical baseline: FACT_SHIPMENT_LINE
-- Source: SUPPLY_CHAIN_DW.RAW.SHIPMENT_LINES
-- Grain: SHIPMENT_LINE_ID
-- Dedup: None (append-only)

INSERT INTO SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE
  (SHIPMENT_LINE_ID, SHIPMENT_ID, ORDER_LINE_ID, PART_ID,
   SHIPPED_QTY, CREATED_AT)
SELECT
  SHIPMENT_LINE_ID, SHIPMENT_ID, ORDER_LINE_ID, PART_ID,
  SHIPPED_QTY, CREATED_AT
FROM SUPPLY_CHAIN_DW.RAW.SHIPMENT_LINES;
