-- Historical baseline: FACT_INVENTORY_SNAPSHOT
-- Source: SUPPLY_CHAIN_DW.RAW.INVENTORY
-- Grain: PLANT_ID + PART_ID
-- Dedup: (PLANT_ID, PART_ID) by LAST_UPDATED_AT DESC

INSERT INTO SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT
  (PLANT_ID, PART_ID, ON_HAND_QTY, RESERVED_QTY, AVAILABLE_QTY,
   SAFETY_STOCK, REORDER_POINT, INVENTORY_STATUS,
   NEEDS_REORDER, BELOW_SAFETY_STOCK, LAST_UPDATED_AT, SNAPSHOT_DATE_KEY)
WITH inventory_dedup AS (
  SELECT *
  FROM (
    SELECT *,
      ROW_NUMBER() OVER (PARTITION BY PLANT_ID, PART_ID ORDER BY LAST_UPDATED_AT DESC) AS rn
    FROM SUPPLY_CHAIN_DW.RAW.INVENTORY
  )
  WHERE rn = 1
)
SELECT
  PLANT_ID,
  PART_ID,
  ON_HAND_QTY,
  RESERVED_QTY,
  AVAILABLE_QTY,
  SAFETY_STOCK,
  REORDER_POINT,
  INVENTORY_STATUS,
  CASE WHEN AVAILABLE_QTY <= REORDER_POINT THEN TRUE ELSE FALSE END AS NEEDS_REORDER,
  CASE WHEN AVAILABLE_QTY <= SAFETY_STOCK THEN TRUE ELSE FALSE END AS BELOW_SAFETY_STOCK,
  LAST_UPDATED_AT,
  LAST_UPDATED_AT::DATE                  AS SNAPSHOT_DATE_KEY
FROM inventory_dedup;
