-- Historical baseline: FACT_SUPPLIER_PERFORMANCE
-- Source: SUPPLY_CHAIN_DW.RAW.SUPPLIER_PERFORMANCE
-- Grain: SUPPLIER_ID + MEASUREMENT_DATE
-- Dedup: (SUPPLIER_ID, MEASUREMENT_DATE) by LAST_UPDATED_AT DESC

INSERT INTO SUPPLY_CHAIN_DW.SILVER.FACT_SUPPLIER_PERFORMANCE
  (SUPPLIER_PERFORMANCE_ID, SUPPLIER_ID, MEASUREMENT_DATE_KEY,
   AVG_LEAD_TIME_DAYS, ON_TIME_DELIVERY_PCT, QUALITY_SCORE,
   FILL_RATE_PCT, RISK_SCORE, LAST_UPDATED_AT)
WITH sp_dedup AS (
  SELECT *
  FROM (
    SELECT *,
      ROW_NUMBER() OVER (PARTITION BY SUPPLIER_ID, MEASUREMENT_DATE ORDER BY LAST_UPDATED_AT DESC) AS rn
    FROM SUPPLY_CHAIN_DW.RAW.SUPPLIER_PERFORMANCE
  )
  WHERE rn = 1
)
SELECT
  SUPPLIER_PERFORMANCE_ID,
  SUPPLIER_ID,
  MEASUREMENT_DATE                       AS MEASUREMENT_DATE_KEY,
  AVG_LEAD_TIME_DAYS,
  ON_TIME_DELIVERY_PCT,
  QUALITY_SCORE,
  FILL_RATE_PCT,
  RISK_SCORE,
  LAST_UPDATED_AT
FROM sp_dedup;
