-- Historical baseline: FACT_SHIPMENT
-- Source: SUPPLY_CHAIN_DW.RAW.SHIPMENTS
-- Grain: SHIPMENT_ID
-- Dedup: SHIPMENT_ID by LAST_UPDATED_AT DESC

INSERT INTO SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT
  (SHIPMENT_ID, SHIPMENT_TYPE, CARRIER_ID, ROUTE_ID, SHIPMENT_STATUS,
   PLANNED_DEPARTURE_AT, ACTUAL_DEPARTURE_AT, PLANNED_DELIVERY_AT,
   ACTUAL_DELIVERY_AT, DEPARTURE_DATE_KEY, DELIVERY_DATE_KEY,
   SHIPPING_COST, ACTUAL_TRANSIT_HOURS, PLANNED_TRANSIT_HOURS,
   IS_ON_TIME, LAST_UPDATED_AT)
WITH shipments_dedup AS (
  SELECT *
  FROM (
    SELECT *,
      ROW_NUMBER() OVER (PARTITION BY SHIPMENT_ID ORDER BY LAST_UPDATED_AT DESC) AS rn
    FROM SUPPLY_CHAIN_DW.RAW.SHIPMENTS
  )
  WHERE rn = 1
)
SELECT
  SHIPMENT_ID,
  SHIPMENT_TYPE,
  CARRIER_ID,
  ROUTE_ID,
  SHIPMENT_STATUS,
  PLANNED_DEPARTURE_AT,
  ACTUAL_DEPARTURE_AT,
  PLANNED_DELIVERY_AT,
  ACTUAL_DELIVERY_AT,
  PLANNED_DEPARTURE_AT::DATE             AS DEPARTURE_DATE_KEY,
  PLANNED_DELIVERY_AT::DATE              AS DELIVERY_DATE_KEY,
  SHIPPING_COST,
  DATEDIFF('HOUR', ACTUAL_DEPARTURE_AT, ACTUAL_DELIVERY_AT) AS ACTUAL_TRANSIT_HOURS,
  DATEDIFF('HOUR', PLANNED_DEPARTURE_AT, PLANNED_DELIVERY_AT) AS PLANNED_TRANSIT_HOURS,
  CASE
    WHEN ACTUAL_DELIVERY_AT IS NULL THEN NULL
    WHEN ACTUAL_DELIVERY_AT <= PLANNED_DELIVERY_AT THEN TRUE
    ELSE FALSE
  END                                     AS IS_ON_TIME,
  LAST_UPDATED_AT
FROM shipments_dedup;
