-- Historical baseline: FACT_SHIPMENT_EVENT
-- Source: SUPPLY_CHAIN_DW.RAW.SHIPMENT_EVENTS
-- Grain: SHIPMENT_EVENT_ID
-- Dedup: None (history table)

INSERT INTO SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT
  (SHIPMENT_EVENT_ID, SHIPMENT_ID, EVENT_TIMESTAMP, EVENT_DATE_KEY,
   EVENT_TYPE, LOCATION_LATITUDE, LOCATION_LONGITUDE, EVENT_DESCRIPTION)
SELECT
  SHIPMENT_EVENT_ID,
  SHIPMENT_ID,
  EVENT_TIMESTAMP,
  EVENT_TIMESTAMP::DATE                  AS EVENT_DATE_KEY,
  EVENT_TYPE,
  LOCATION_LATITUDE,
  LOCATION_LONGITUDE,
  EVENT_DESCRIPTION
FROM SUPPLY_CHAIN_DW.RAW.SHIPMENT_EVENTS;
