-- Historical baseline: FACT_VEHICLE_TELEMETRY
-- Source: SUPPLY_CHAIN_DW.RAW.VEHICLE_TELEMETRY
-- Grain: TELEMETRY_ID
-- Dedup: None (history table)

INSERT INTO SUPPLY_CHAIN_DW.SILVER.FACT_VEHICLE_TELEMETRY
  (TELEMETRY_ID, VEHICLE_ID, SHIPMENT_ID, EVENT_TIMESTAMP, EVENT_DATE_KEY,
   LATITUDE, LONGITUDE, SPEED_KMPH, VEHICLE_STATUS, DISTANCE_TRAVELLED_KM)
SELECT
  TELEMETRY_ID,
  VEHICLE_ID,
  SHIPMENT_ID,
  EVENT_TIMESTAMP,
  EVENT_TIMESTAMP::DATE                  AS EVENT_DATE_KEY,
  LATITUDE,
  LONGITUDE,
  SPEED_KMPH,
  VEHICLE_STATUS,
  DISTANCE_TRAVELLED_KM
FROM SUPPLY_CHAIN_DW.RAW.VEHICLE_TELEMETRY;
