-- =============================================================================
-- DERIVED COLUMN CHECKS
-- Validates computed/derived columns match their source expressions
-- =============================================================================

-- ===== FACT_SHIPMENT: IS_ON_TIME =====
-- Correct logic: NULL when ACTUAL_DELIVERY_AT IS NULL,
--   TRUE when ACTUAL_DELIVERY_AT <= PLANNED_DELIVERY_AT, FALSE otherwise
SELECT 'FACT_SHIPMENT.IS_ON_TIME (NULL when not delivered)' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT
WHERE ACTUAL_DELIVERY_AT IS NULL AND IS_ON_TIME IS NOT NULL;

SELECT 'FACT_SHIPMENT.IS_ON_TIME (TRUE when on time)' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT
WHERE ACTUAL_DELIVERY_AT IS NOT NULL
  AND ACTUAL_DELIVERY_AT <= PLANNED_DELIVERY_AT
  AND IS_ON_TIME != TRUE;

SELECT 'FACT_SHIPMENT.IS_ON_TIME (FALSE when late)' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT
WHERE ACTUAL_DELIVERY_AT IS NOT NULL
  AND ACTUAL_DELIVERY_AT > PLANNED_DELIVERY_AT
  AND IS_ON_TIME != FALSE;

-- ===== FACT_SHIPMENT: ACTUAL_TRANSIT_HOURS =====
SELECT 'FACT_SHIPMENT.ACTUAL_TRANSIT_HOURS' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT
WHERE ACTUAL_DELIVERY_AT IS NOT NULL
  AND ACTUAL_TRANSIT_HOURS != DATEDIFF('HOUR', ACTUAL_DEPARTURE_AT, ACTUAL_DELIVERY_AT);

-- NULL when not yet delivered
SELECT 'FACT_SHIPMENT.ACTUAL_TRANSIT_HOURS (NULL when not delivered)' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT
WHERE ACTUAL_DELIVERY_AT IS NULL AND ACTUAL_TRANSIT_HOURS IS NOT NULL;

-- ===== FACT_SHIPMENT: PLANNED_TRANSIT_HOURS =====
SELECT 'FACT_SHIPMENT.PLANNED_TRANSIT_HOURS' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT
WHERE PLANNED_TRANSIT_HOURS != DATEDIFF('HOUR', PLANNED_DEPARTURE_AT, PLANNED_DELIVERY_AT);

-- ===== FACT_INVENTORY_SNAPSHOT: NEEDS_REORDER =====
SELECT 'FACT_INVENTORY_SNAPSHOT.NEEDS_REORDER' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT
WHERE NEEDS_REORDER != (CASE WHEN AVAILABLE_QTY <= REORDER_POINT THEN TRUE ELSE FALSE END);

-- ===== FACT_INVENTORY_SNAPSHOT: BELOW_SAFETY_STOCK =====
SELECT 'FACT_INVENTORY_SNAPSHOT.BELOW_SAFETY_STOCK' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT
WHERE BELOW_SAFETY_STOCK != (CASE WHEN AVAILABLE_QTY <= SAFETY_STOCK THEN TRUE ELSE FALSE END);

-- ===== FACT_SHIPMENT: DATE_KEY derivations =====
SELECT 'FACT_SHIPMENT.DEPARTURE_DATE_KEY' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT
WHERE DEPARTURE_DATE_KEY != PLANNED_DEPARTURE_AT::DATE;

SELECT 'FACT_SHIPMENT.DELIVERY_DATE_KEY' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT
WHERE DELIVERY_DATE_KEY != PLANNED_DELIVERY_AT::DATE;

-- ===== FACT_SHIPMENT_EVENT: EVENT_DATE_KEY =====
SELECT 'FACT_SHIPMENT_EVENT.EVENT_DATE_KEY' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT
WHERE EVENT_DATE_KEY != EVENT_TIMESTAMP::DATE;

-- ===== FACT_VEHICLE_TELEMETRY: EVENT_DATE_KEY =====
SELECT 'FACT_VEHICLE_TELEMETRY.EVENT_DATE_KEY' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_VEHICLE_TELEMETRY
WHERE EVENT_DATE_KEY != EVENT_TIMESTAMP::DATE;

-- ===== FACT_INVENTORY_SNAPSHOT: SNAPSHOT_DATE_KEY =====
SELECT 'FACT_INVENTORY_SNAPSHOT.SNAPSHOT_DATE_KEY' AS check_name,
       COUNT(*) AS violation_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT
WHERE SNAPSHOT_DATE_KEY != LAST_UPDATED_AT::DATE;
