-- =============================================================================
-- DIMENSION KEY UNIQUENESS CHECKS
-- Validates that each dimension's business key is unique and non-null
-- =============================================================================

-- DIM_DATE: DATE_KEY not null, unique
SELECT 'DIM_DATE.DATE_KEY' AS check_name,
       SUM(CASE WHEN DATE_KEY IS NULL THEN 1 ELSE 0 END) AS null_count,
       COUNT(*) - COUNT(DISTINCT DATE_KEY) AS duplicate_count,
       CASE WHEN SUM(CASE WHEN DATE_KEY IS NULL THEN 1 ELSE 0 END) = 0
             AND COUNT(*) = COUNT(DISTINCT DATE_KEY) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_DATE;

-- DIM_CUSTOMER: CUSTOMER_ID not null, unique
SELECT 'DIM_CUSTOMER.CUSTOMER_ID' AS check_name,
       SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS null_count,
       COUNT(*) - COUNT(DISTINCT CUSTOMER_ID) AS duplicate_count,
       CASE WHEN SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) = 0
             AND COUNT(*) = COUNT(DISTINCT CUSTOMER_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_CUSTOMER;

-- DIM_PART: PART_ID not null, unique
SELECT 'DIM_PART.PART_ID' AS check_name,
       SUM(CASE WHEN PART_ID IS NULL THEN 1 ELSE 0 END) AS null_count,
       COUNT(*) - COUNT(DISTINCT PART_ID) AS duplicate_count,
       CASE WHEN SUM(CASE WHEN PART_ID IS NULL THEN 1 ELSE 0 END) = 0
             AND COUNT(*) = COUNT(DISTINCT PART_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_PART;

-- DIM_PLANT: PLANT_ID not null, unique
SELECT 'DIM_PLANT.PLANT_ID' AS check_name,
       SUM(CASE WHEN PLANT_ID IS NULL THEN 1 ELSE 0 END) AS null_count,
       COUNT(*) - COUNT(DISTINCT PLANT_ID) AS duplicate_count,
       CASE WHEN SUM(CASE WHEN PLANT_ID IS NULL THEN 1 ELSE 0 END) = 0
             AND COUNT(*) = COUNT(DISTINCT PLANT_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_PLANT;

-- DIM_SUPPLIER: SUPPLIER_ID not null, unique
SELECT 'DIM_SUPPLIER.SUPPLIER_ID' AS check_name,
       SUM(CASE WHEN SUPPLIER_ID IS NULL THEN 1 ELSE 0 END) AS null_count,
       COUNT(*) - COUNT(DISTINCT SUPPLIER_ID) AS duplicate_count,
       CASE WHEN SUM(CASE WHEN SUPPLIER_ID IS NULL THEN 1 ELSE 0 END) = 0
             AND COUNT(*) = COUNT(DISTINCT SUPPLIER_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_SUPPLIER;

-- DIM_CARRIER: CARRIER_ID not null, unique
SELECT 'DIM_CARRIER.CARRIER_ID' AS check_name,
       SUM(CASE WHEN CARRIER_ID IS NULL THEN 1 ELSE 0 END) AS null_count,
       COUNT(*) - COUNT(DISTINCT CARRIER_ID) AS duplicate_count,
       CASE WHEN SUM(CASE WHEN CARRIER_ID IS NULL THEN 1 ELSE 0 END) = 0
             AND COUNT(*) = COUNT(DISTINCT CARRIER_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_CARRIER;

-- DIM_ROUTE: ROUTE_ID not null, unique
SELECT 'DIM_ROUTE.ROUTE_ID' AS check_name,
       SUM(CASE WHEN ROUTE_ID IS NULL THEN 1 ELSE 0 END) AS null_count,
       COUNT(*) - COUNT(DISTINCT ROUTE_ID) AS duplicate_count,
       CASE WHEN SUM(CASE WHEN ROUTE_ID IS NULL THEN 1 ELSE 0 END) = 0
             AND COUNT(*) = COUNT(DISTINCT ROUTE_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_ROUTE;
