-- =============================================================================
-- GRAIN UNIQUENESS CHECKS
-- Validates primary key / composite key uniqueness for all 15 Silver tables
-- =============================================================================

-- ===== DIMENSIONS =====

-- DIM_DATE: unique on DATE_KEY
SELECT 'DIM_DATE' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT DATE_KEY) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT DATE_KEY) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_DATE;

-- DIM_CUSTOMER: unique on CUSTOMER_ID
SELECT 'DIM_CUSTOMER' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT CUSTOMER_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT CUSTOMER_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_CUSTOMER;

-- DIM_PART: unique on PART_ID
SELECT 'DIM_PART' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT PART_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT PART_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_PART;

-- DIM_PLANT: unique on PLANT_ID
SELECT 'DIM_PLANT' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT PLANT_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT PLANT_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_PLANT;

-- DIM_SUPPLIER: unique on SUPPLIER_ID
SELECT 'DIM_SUPPLIER' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT SUPPLIER_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT SUPPLIER_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_SUPPLIER;

-- DIM_CARRIER: unique on CARRIER_ID
SELECT 'DIM_CARRIER' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT CARRIER_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT CARRIER_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_CARRIER;

-- DIM_ROUTE: unique on ROUTE_ID
SELECT 'DIM_ROUTE' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT ROUTE_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT ROUTE_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.DIM_ROUTE;

-- ===== FACTS =====

-- FACT_ORDER_LINE: unique on ORDER_LINE_ID
SELECT 'FACT_ORDER_LINE' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT ORDER_LINE_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT ORDER_LINE_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE;

-- FACT_SHIPMENT: unique on SHIPMENT_ID
SELECT 'FACT_SHIPMENT' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT SHIPMENT_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT SHIPMENT_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT;

-- FACT_SHIPMENT_LINE: unique on SHIPMENT_LINE_ID
SELECT 'FACT_SHIPMENT_LINE' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT SHIPMENT_LINE_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT SHIPMENT_LINE_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE;

-- FACT_SHIPMENT_EVENT: unique on SHIPMENT_EVENT_ID
SELECT 'FACT_SHIPMENT_EVENT' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT SHIPMENT_EVENT_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT SHIPMENT_EVENT_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT;

-- FACT_INVENTORY_SNAPSHOT: unique on (PLANT_ID, PART_ID)
SELECT 'FACT_INVENTORY_SNAPSHOT' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT PLANT_ID || '|' || PART_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT PLANT_ID || '|' || PART_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT;

-- FACT_SUPPLIER_PERFORMANCE: unique on (SUPPLIER_ID, MEASUREMENT_DATE_KEY)
SELECT 'FACT_SUPPLIER_PERFORMANCE' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT SUPPLIER_ID || '|' || MEASUREMENT_DATE_KEY) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT SUPPLIER_ID || '|' || MEASUREMENT_DATE_KEY) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SUPPLIER_PERFORMANCE;

-- FACT_VEHICLE_TELEMETRY: unique on TELEMETRY_ID
SELECT 'FACT_VEHICLE_TELEMETRY' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT TELEMETRY_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT TELEMETRY_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_VEHICLE_TELEMETRY;

-- ===== BRIDGE =====

-- BRIDGE_SUPPLIER_PART: unique on (SUPPLIER_ID, PART_ID)
SELECT 'BRIDGE_SUPPLIER_PART' AS table_name,
       COUNT(*) AS total_rows,
       COUNT(DISTINCT SUPPLIER_ID || '|' || PART_ID) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT SUPPLIER_ID || '|' || PART_ID) THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART;
