-- =============================================================================
-- REFERENTIAL INTEGRITY CHECKS
-- Validates FK relationships between facts/bridge and dimensions
-- Each query returns orphan count; 0 = PASS
-- =============================================================================

-- ===== FACT_ORDER_LINE =====

-- → DIM_CUSTOMER
SELECT 'FACT_ORDER_LINE → DIM_CUSTOMER' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_CUSTOMER d ON f.CUSTOMER_ID = d.CUSTOMER_ID
WHERE d.CUSTOMER_ID IS NULL;

-- → DIM_PLANT
SELECT 'FACT_ORDER_LINE → DIM_PLANT' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_PLANT d ON f.PLANT_ID = d.PLANT_ID
WHERE d.PLANT_ID IS NULL;

-- → DIM_PART
SELECT 'FACT_ORDER_LINE → DIM_PART' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_PART d ON f.PART_ID = d.PART_ID
WHERE d.PART_ID IS NULL;

-- → DIM_DATE (ORDER_DATE_KEY)
SELECT 'FACT_ORDER_LINE.ORDER_DATE_KEY → DIM_DATE' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_DATE d ON f.ORDER_DATE_KEY = d.DATE_KEY
WHERE d.DATE_KEY IS NULL AND f.ORDER_DATE_KEY IS NOT NULL;

-- → DIM_DATE (REQUESTED_DELIVERY_DATE_KEY)
SELECT 'FACT_ORDER_LINE.REQUESTED_DELIVERY_DATE_KEY → DIM_DATE' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_DATE d ON f.REQUESTED_DELIVERY_DATE_KEY = d.DATE_KEY
WHERE d.DATE_KEY IS NULL AND f.REQUESTED_DELIVERY_DATE_KEY IS NOT NULL;

-- ===== FACT_SHIPMENT =====

-- → DIM_CARRIER
SELECT 'FACT_SHIPMENT → DIM_CARRIER' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_CARRIER d ON f.CARRIER_ID = d.CARRIER_ID
WHERE d.CARRIER_ID IS NULL;

-- → DIM_ROUTE
SELECT 'FACT_SHIPMENT → DIM_ROUTE' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_ROUTE d ON f.ROUTE_ID = d.ROUTE_ID
WHERE d.ROUTE_ID IS NULL;

-- → DIM_DATE (DEPARTURE_DATE_KEY)
SELECT 'FACT_SHIPMENT.DEPARTURE_DATE_KEY → DIM_DATE' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_DATE d ON f.DEPARTURE_DATE_KEY = d.DATE_KEY
WHERE d.DATE_KEY IS NULL AND f.DEPARTURE_DATE_KEY IS NOT NULL;

-- → DIM_DATE (DELIVERY_DATE_KEY)
SELECT 'FACT_SHIPMENT.DELIVERY_DATE_KEY → DIM_DATE' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_DATE d ON f.DELIVERY_DATE_KEY = d.DATE_KEY
WHERE d.DATE_KEY IS NULL AND f.DELIVERY_DATE_KEY IS NOT NULL;

-- ===== FACT_SHIPMENT_LINE =====

-- → FACT_SHIPMENT
SELECT 'FACT_SHIPMENT_LINE → FACT_SHIPMENT' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE sl
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT s ON sl.SHIPMENT_ID = s.SHIPMENT_ID
WHERE s.SHIPMENT_ID IS NULL;

-- → FACT_ORDER_LINE
SELECT 'FACT_SHIPMENT_LINE → FACT_ORDER_LINE' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE sl
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE ol ON sl.ORDER_LINE_ID = ol.ORDER_LINE_ID
WHERE ol.ORDER_LINE_ID IS NULL;

-- → DIM_PART
SELECT 'FACT_SHIPMENT_LINE → DIM_PART' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE sl
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_PART d ON sl.PART_ID = d.PART_ID
WHERE d.PART_ID IS NULL;

-- ===== FACT_SHIPMENT_EVENT =====

-- → FACT_SHIPMENT
SELECT 'FACT_SHIPMENT_EVENT → FACT_SHIPMENT' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT e
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT s ON e.SHIPMENT_ID = s.SHIPMENT_ID
WHERE s.SHIPMENT_ID IS NULL;

-- → DIM_DATE (EVENT_DATE_KEY)
SELECT 'FACT_SHIPMENT_EVENT.EVENT_DATE_KEY → DIM_DATE' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_EVENT f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_DATE d ON f.EVENT_DATE_KEY = d.DATE_KEY
WHERE d.DATE_KEY IS NULL AND f.EVENT_DATE_KEY IS NOT NULL;

-- ===== FACT_INVENTORY_SNAPSHOT =====

-- → DIM_PLANT
SELECT 'FACT_INVENTORY_SNAPSHOT → DIM_PLANT' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_PLANT d ON f.PLANT_ID = d.PLANT_ID
WHERE d.PLANT_ID IS NULL;

-- → DIM_PART
SELECT 'FACT_INVENTORY_SNAPSHOT → DIM_PART' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_PART d ON f.PART_ID = d.PART_ID
WHERE d.PART_ID IS NULL;

-- → DIM_DATE (SNAPSHOT_DATE_KEY)
SELECT 'FACT_INVENTORY_SNAPSHOT.SNAPSHOT_DATE_KEY → DIM_DATE' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_INVENTORY_SNAPSHOT f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_DATE d ON f.SNAPSHOT_DATE_KEY = d.DATE_KEY
WHERE d.DATE_KEY IS NULL AND f.SNAPSHOT_DATE_KEY IS NOT NULL;

-- ===== FACT_SUPPLIER_PERFORMANCE =====

-- → DIM_SUPPLIER
SELECT 'FACT_SUPPLIER_PERFORMANCE → DIM_SUPPLIER' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SUPPLIER_PERFORMANCE f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_SUPPLIER d ON f.SUPPLIER_ID = d.SUPPLIER_ID
WHERE d.SUPPLIER_ID IS NULL;

-- → DIM_DATE (MEASUREMENT_DATE_KEY)
SELECT 'FACT_SUPPLIER_PERFORMANCE.MEASUREMENT_DATE_KEY → DIM_DATE' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_SUPPLIER_PERFORMANCE f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_DATE d ON f.MEASUREMENT_DATE_KEY = d.DATE_KEY
WHERE d.DATE_KEY IS NULL AND f.MEASUREMENT_DATE_KEY IS NOT NULL;

-- ===== FACT_VEHICLE_TELEMETRY =====

-- → FACT_SHIPMENT
SELECT 'FACT_VEHICLE_TELEMETRY → FACT_SHIPMENT' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_VEHICLE_TELEMETRY f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT s ON f.SHIPMENT_ID = s.SHIPMENT_ID
WHERE s.SHIPMENT_ID IS NULL;

-- → DIM_DATE (EVENT_DATE_KEY)
SELECT 'FACT_VEHICLE_TELEMETRY.EVENT_DATE_KEY → DIM_DATE' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.FACT_VEHICLE_TELEMETRY f
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_DATE d ON f.EVENT_DATE_KEY = d.DATE_KEY
WHERE d.DATE_KEY IS NULL AND f.EVENT_DATE_KEY IS NOT NULL;

-- ===== BRIDGE_SUPPLIER_PART =====

-- → DIM_SUPPLIER
SELECT 'BRIDGE_SUPPLIER_PART → DIM_SUPPLIER' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART b
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_SUPPLIER d ON b.SUPPLIER_ID = d.SUPPLIER_ID
WHERE d.SUPPLIER_ID IS NULL;

-- → DIM_PART
SELECT 'BRIDGE_SUPPLIER_PART → DIM_PART' AS check_name,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM SUPPLY_CHAIN_DW.SILVER.BRIDGE_SUPPLIER_PART b
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_PART d ON b.PART_ID = d.PART_ID
WHERE d.PART_ID IS NULL;
