-- =============================================================================
-- Populate MART_ORDER_FULFILLMENT
-- =============================================================================
-- Populates SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT from Silver sources.
-- Reuses archived V2.5.0 design (37 columns).
--
-- Two-branch architecture:
--   Branch 1: line-level fulfillment + lateness → ORDER_ID
--   Branch 2: shipment metrics → ORDER_ID
--
-- Prerequisites: V3.4.0 (empty table) must be deployed.
-- Idempotent: TRUNCATE + INSERT pattern.
-- =============================================================================

TRUNCATE TABLE SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT;

INSERT INTO SUPPLY_CHAIN_DW.GOLD.MART_ORDER_FULFILLMENT (
    ORDER_ID, ANALYSIS_AS_OF_DATE,
    CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_SEGMENT, PLANT_ID, PLANT_NAME,
    ORDER_DATE, REQUESTED_DELIVERY_DATE,
    FULFILLMENT_STATE,
    TOTAL_ORDER_LINE_COUNT, CANCELLED_LINE_COUNT, ACTIVE_LINE_COUNT,
    ORDERED_QTY, ACTIVE_ORDERED_QTY, RAW_SHIPPED_QTY, EFFECTIVE_SHIPPED_QTY,
    OUTSTANDING_QTY, OVER_SHIPPED_QTY, FULFILLMENT_PCT,
    ORDER_VALUE, ACTIVE_ORDER_VALUE, OUTSTANDING_VALUE,
    SHIPMENT_COUNT, LATE_SHIPMENT_COUNT,
    CURRENT_DELAY_DAYS, MAX_DELIVERED_DELAY_DAYS, LAST_ACTUAL_DELIVERY_DATE,
    IS_FULFILLED, IS_PARTIALLY_FULFILLED, IS_UNFULFILLED, IS_CANCELLED,
    IS_CURRENT_LATE, IS_DELIVERED_LATE, IS_LATE,
    HAS_DELAYED_SHIPMENT, HAS_OVER_SHIPMENT
)
WITH analysis_anchor AS (
    SELECT MAX(LINE_UPDATED_AT)::DATE AS ANALYSIS_AS_OF_DATE
    FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE
),

-- =========================================================================
-- BRANCH 1: Line-Level Fulfillment and Lateness → ORDER_ID
-- =========================================================================

-- Step 1a: Aggregate shipment lines to ORDER_LINE_ID.
-- Fan-out prevention: SUM + MAX GROUP BY ORDER_LINE_ID → 1 row per line.
-- Joins FACT_SHIPMENT only for MAX(ACTUAL_DELIVERY_AT) — M:1 on SHIPMENT_ID.
shipment_per_line AS (
    SELECT
        fsl.ORDER_LINE_ID,
        SUM(fsl.SHIPPED_QTY)            AS LINE_SHIPPED_QTY,
        MAX(fs.ACTUAL_DELIVERY_AT)::DATE AS LINE_MAX_ACTUAL_DELIVERY_DATE
    FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE fsl
    JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT fs
        ON fsl.SHIPMENT_ID = fs.SHIPMENT_ID
    GROUP BY fsl.ORDER_LINE_ID
),

-- Step 1b: Enrich every order line with line-safe fulfillment and lateness.
-- LEFT JOIN preserves lines with no shipments.
-- Line-safe capping: LEAST(shipped, ordered) prevents shipped > ordered.
line_enriched AS (
    SELECT
        fol.ORDER_LINE_ID,
        fol.ORDER_ID,
        fol.CUSTOMER_ID,
        fol.PLANT_ID,
        fol.ORDER_DATE_KEY,
        fol.REQUESTED_DELIVERY_DATE_KEY,
        fol.LINE_STATUS,
        fol.ORDERED_QTY,
        fol.UNIT_PRICE,
        fol.LINE_AMOUNT,
        a.ANALYSIS_AS_OF_DATE,
        spl.LINE_SHIPPED_QTY,
        LEAST(COALESCE(spl.LINE_SHIPPED_QTY, 0), fol.ORDERED_QTY)
            AS LINE_EFFECTIVE_SHIPPED_QTY,
        GREATEST(fol.ORDERED_QTY - COALESCE(spl.LINE_SHIPPED_QTY, 0), 0)
            AS LINE_OUTSTANDING_QTY,
        GREATEST(COALESCE(spl.LINE_SHIPPED_QTY, 0) - fol.ORDERED_QTY, 0)
            AS LINE_OVER_SHIPPED_QTY,
        spl.LINE_MAX_ACTUAL_DELIVERY_DATE,
        CASE
            WHEN fol.LINE_STATUS != 'CANCELLED'
                 AND GREATEST(fol.ORDERED_QTY - COALESCE(spl.LINE_SHIPPED_QTY, 0), 0) > 0
                 AND fol.REQUESTED_DELIVERY_DATE_KEY < a.ANALYSIS_AS_OF_DATE
            THEN TRUE ELSE FALSE
        END AS LINE_IS_CURRENT_LATE,
        CASE
            WHEN fol.LINE_STATUS != 'CANCELLED'
                 AND GREATEST(fol.ORDERED_QTY - COALESCE(spl.LINE_SHIPPED_QTY, 0), 0) > 0
                 AND fol.REQUESTED_DELIVERY_DATE_KEY < a.ANALYSIS_AS_OF_DATE
            THEN DATEDIFF('DAY', fol.REQUESTED_DELIVERY_DATE_KEY, a.ANALYSIS_AS_OF_DATE)
        END AS LINE_CURRENT_DELAY_DAYS,
        CASE
            WHEN fol.LINE_STATUS != 'CANCELLED'
                 AND spl.LINE_MAX_ACTUAL_DELIVERY_DATE IS NOT NULL
                 AND spl.LINE_MAX_ACTUAL_DELIVERY_DATE > fol.REQUESTED_DELIVERY_DATE_KEY
            THEN TRUE ELSE FALSE
        END AS LINE_IS_DELIVERED_LATE,
        CASE
            WHEN fol.LINE_STATUS != 'CANCELLED'
                 AND spl.LINE_MAX_ACTUAL_DELIVERY_DATE IS NOT NULL
                 AND spl.LINE_MAX_ACTUAL_DELIVERY_DATE > fol.REQUESTED_DELIVERY_DATE_KEY
            THEN DATEDIFF('DAY', fol.REQUESTED_DELIVERY_DATE_KEY, spl.LINE_MAX_ACTUAL_DELIVERY_DATE)
        END AS LINE_DELIVERED_DELAY_DAYS
    FROM SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE fol
    CROSS JOIN analysis_anchor a
    LEFT JOIN shipment_per_line spl ON fol.ORDER_LINE_ID = spl.ORDER_LINE_ID
),

-- Step 1c: Aggregate to ORDER_ID.
-- Fan-out prevention: GROUP BY ORDER_ID collapses all lines.
order_fulfillment AS (
    SELECT
        ORDER_ID,
        MAX(ANALYSIS_AS_OF_DATE)             AS ANALYSIS_AS_OF_DATE,
        ANY_VALUE(CUSTOMER_ID)               AS CUSTOMER_ID,
        ANY_VALUE(PLANT_ID)                  AS PLANT_ID,
        MIN(ORDER_DATE_KEY)                  AS ORDER_DATE,
        MAX(CASE WHEN LINE_STATUS != 'CANCELLED' THEN REQUESTED_DELIVERY_DATE_KEY END)
            AS REQUESTED_DELIVERY_DATE,
        COUNT(*)                             AS TOTAL_ORDER_LINE_COUNT,
        SUM(CASE WHEN LINE_STATUS = 'CANCELLED' THEN 1 ELSE 0 END)
            AS CANCELLED_LINE_COUNT,
        SUM(ORDERED_QTY)                     AS ORDERED_QTY,
        SUM(CASE WHEN LINE_STATUS != 'CANCELLED' THEN ORDERED_QTY ELSE 0 END)
            AS ACTIVE_ORDERED_QTY,
        SUM(CASE WHEN LINE_STATUS != 'CANCELLED' THEN COALESCE(LINE_SHIPPED_QTY, 0) ELSE 0 END)
            AS RAW_SHIPPED_QTY,
        SUM(CASE WHEN LINE_STATUS != 'CANCELLED' THEN LINE_EFFECTIVE_SHIPPED_QTY ELSE 0 END)
            AS EFFECTIVE_SHIPPED_QTY,
        SUM(CASE WHEN LINE_STATUS != 'CANCELLED' THEN LINE_OUTSTANDING_QTY ELSE 0 END)
            AS OUTSTANDING_QTY,
        SUM(CASE WHEN LINE_STATUS != 'CANCELLED' THEN LINE_OVER_SHIPPED_QTY ELSE 0 END)
            AS OVER_SHIPPED_QTY,
        SUM(LINE_AMOUNT)                     AS ORDER_VALUE,
        SUM(CASE WHEN LINE_STATUS != 'CANCELLED' THEN LINE_AMOUNT ELSE 0 END)
            AS ACTIVE_ORDER_VALUE,
        SUM(CASE WHEN LINE_STATUS != 'CANCELLED' THEN LINE_OUTSTANDING_QTY * UNIT_PRICE ELSE 0 END)
            AS OUTSTANDING_VALUE,
        MAX(LINE_IS_CURRENT_LATE::INT) = 1   AS IS_CURRENT_LATE,
        MAX(CASE WHEN LINE_IS_CURRENT_LATE THEN LINE_CURRENT_DELAY_DAYS END)
            AS CURRENT_DELAY_DAYS,
        MAX(LINE_IS_DELIVERED_LATE::INT) = 1 AS IS_DELIVERED_LATE,
        MAX(CASE WHEN LINE_IS_DELIVERED_LATE THEN LINE_DELIVERED_DELAY_DAYS END)
            AS MAX_DELIVERED_DELAY_DAYS,
        MAX(CASE WHEN LINE_STATUS != 'CANCELLED' THEN LINE_MAX_ACTUAL_DELIVERY_DATE END)
            AS LAST_ACTUAL_DELIVERY_DATE
    FROM line_enriched
    GROUP BY ORDER_ID
),

-- =========================================================================
-- BRANCH 2: Shipment Metrics → ORDER_ID
-- Fan-out prevention: SELECT DISTINCT (ORDER_ID, SHIPMENT_ID, IS_ON_TIME)
-- then GROUP BY ORDER_ID with COUNT DISTINCT.
-- =========================================================================
order_shipment_pairs AS (
    SELECT DISTINCT
        fol.ORDER_ID,
        fsl.SHIPMENT_ID,
        fs.IS_ON_TIME
    FROM SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT_LINE fsl
    JOIN SUPPLY_CHAIN_DW.SILVER.FACT_ORDER_LINE fol ON fsl.ORDER_LINE_ID = fol.ORDER_LINE_ID
    JOIN SUPPLY_CHAIN_DW.SILVER.FACT_SHIPMENT fs ON fsl.SHIPMENT_ID = fs.SHIPMENT_ID
    WHERE fol.LINE_STATUS != 'CANCELLED'
),
order_shipments AS (
    SELECT
        ORDER_ID,
        COUNT(DISTINCT SHIPMENT_ID)                                     AS SHIPMENT_COUNT,
        COUNT(DISTINCT CASE WHEN IS_ON_TIME = FALSE THEN SHIPMENT_ID END) AS LATE_SHIPMENT_COUNT
    FROM order_shipment_pairs
    GROUP BY ORDER_ID
)

-- =========================================================================
-- FINAL ASSEMBLY
-- All joins 1:1 or M:1 on ORDER_ID grain.
-- =========================================================================
SELECT
    orf.ORDER_ID,
    orf.ANALYSIS_AS_OF_DATE,
    orf.CUSTOMER_ID,
    dc.CUSTOMER_NAME,
    dc.CUSTOMER_SEGMENT,
    orf.PLANT_ID,
    dp.PLANT_NAME,
    orf.ORDER_DATE,
    orf.REQUESTED_DELIVERY_DATE,

    CASE
        WHEN orf.CANCELLED_LINE_COUNT = orf.TOTAL_ORDER_LINE_COUNT THEN 'CANCELLED'
        WHEN orf.OUTSTANDING_QTY = 0 THEN 'FULFILLED'
        WHEN orf.EFFECTIVE_SHIPPED_QTY > 0 THEN 'PARTIALLY_FULFILLED'
        ELSE 'UNFULFILLED'
    END AS FULFILLMENT_STATE,

    orf.TOTAL_ORDER_LINE_COUNT,
    orf.CANCELLED_LINE_COUNT,
    orf.TOTAL_ORDER_LINE_COUNT - orf.CANCELLED_LINE_COUNT AS ACTIVE_LINE_COUNT,
    orf.ORDERED_QTY,
    orf.ACTIVE_ORDERED_QTY,
    orf.RAW_SHIPPED_QTY,
    orf.EFFECTIVE_SHIPPED_QTY,
    orf.OUTSTANDING_QTY,
    orf.OVER_SHIPPED_QTY,
    ROUND(100.0 * orf.EFFECTIVE_SHIPPED_QTY / NULLIF(orf.ACTIVE_ORDERED_QTY, 0), 2)
        AS FULFILLMENT_PCT,

    orf.ORDER_VALUE,
    orf.ACTIVE_ORDER_VALUE,
    orf.OUTSTANDING_VALUE,

    COALESCE(os.SHIPMENT_COUNT, 0)       AS SHIPMENT_COUNT,
    COALESCE(os.LATE_SHIPMENT_COUNT, 0)  AS LATE_SHIPMENT_COUNT,

    orf.CURRENT_DELAY_DAYS,
    orf.MAX_DELIVERED_DELAY_DAYS,
    orf.LAST_ACTUAL_DELIVERY_DATE,

    (CASE WHEN orf.CANCELLED_LINE_COUNT = orf.TOTAL_ORDER_LINE_COUNT THEN 'CANCELLED' WHEN orf.OUTSTANDING_QTY = 0 THEN 'FULFILLED' WHEN orf.EFFECTIVE_SHIPPED_QTY > 0 THEN 'PARTIALLY_FULFILLED' ELSE 'UNFULFILLED' END) = 'FULFILLED'
        AS IS_FULFILLED,
    (CASE WHEN orf.CANCELLED_LINE_COUNT = orf.TOTAL_ORDER_LINE_COUNT THEN 'CANCELLED' WHEN orf.OUTSTANDING_QTY = 0 THEN 'FULFILLED' WHEN orf.EFFECTIVE_SHIPPED_QTY > 0 THEN 'PARTIALLY_FULFILLED' ELSE 'UNFULFILLED' END) = 'PARTIALLY_FULFILLED'
        AS IS_PARTIALLY_FULFILLED,
    (CASE WHEN orf.CANCELLED_LINE_COUNT = orf.TOTAL_ORDER_LINE_COUNT THEN 'CANCELLED' WHEN orf.OUTSTANDING_QTY = 0 THEN 'FULFILLED' WHEN orf.EFFECTIVE_SHIPPED_QTY > 0 THEN 'PARTIALLY_FULFILLED' ELSE 'UNFULFILLED' END) = 'UNFULFILLED'
        AS IS_UNFULFILLED,
    (CASE WHEN orf.CANCELLED_LINE_COUNT = orf.TOTAL_ORDER_LINE_COUNT THEN 'CANCELLED' WHEN orf.OUTSTANDING_QTY = 0 THEN 'FULFILLED' WHEN orf.EFFECTIVE_SHIPPED_QTY > 0 THEN 'PARTIALLY_FULFILLED' ELSE 'UNFULFILLED' END) = 'CANCELLED'
        AS IS_CANCELLED,
    orf.IS_CURRENT_LATE,
    orf.IS_DELIVERED_LATE,
    (orf.IS_CURRENT_LATE OR orf.IS_DELIVERED_LATE) AS IS_LATE,
    (COALESCE(os.LATE_SHIPMENT_COUNT, 0) > 0) AS HAS_DELAYED_SHIPMENT,
    (orf.OVER_SHIPPED_QTY > 0) AS HAS_OVER_SHIPMENT

FROM order_fulfillment orf
LEFT JOIN order_shipments os ON orf.ORDER_ID = os.ORDER_ID
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_CUSTOMER dc ON orf.CUSTOMER_ID = dc.CUSTOMER_ID
LEFT JOIN SUPPLY_CHAIN_DW.SILVER.DIM_PLANT dp ON orf.PLANT_ID = dp.PLANT_ID;
